const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const data=new Map(),spoken=[];
const ctx={localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},window:{speechSynthesis:{cancel(){},speak:u=>spoken.push(u.text)}},SpeechSynthesisUtterance:class{constructor(text){this.text=text}},URL,Date,Number,Object,Math,Set,Map};
vm.createContext(ctx);
for(const file of ['progress.js','content.js','zone.js','import.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);
vm.runInContext('this.Z=LiplipZone;this.I=LiplipImporter;',ctx);
const {Z,I}=ctx,header=Array.from(I.HEADERS),base=(process,type)=>{const row=Array(20).fill('');row[0]=process;row[1]=row[2]=row[3]=1;row[4]=type;row[19]='https://liplip.pages.dev/images/book.svg';return row};
const word=base('vocab','imageWord');word[5]='book';word[6]='كتاب';word[7]='This book is new.';
const choice=base('checkpointVocab','imageChoice');choice[8]='ما هذا؟';choice[10]='book';choice[11]='pen';choice[12]='bag';choice[13]=1;choice[14]='It is a book.';
const write=base('checkpointVocab','imageWrite');write[8]='اكتب ما في الصورة';write[15]='book';write[14]='It is a book.';
const speak=base('checkpointVocab','imageSpeak');speak[8]='انطق ما في الصورة';speak[15]='book';speak[14]='It is a book.';
assert.equal(I.parseRows([[...header.slice(0,5),...header.slice(6),'Image link'],word,choice,write,speak],Z.validateItem).count,4);
assert.equal(I.parseRows([header.slice(0,5).concat(header.slice(6,20).slice(0,14)),['vocab',1,1,1,'word','book','كتاب','This book is new.']],Z.validateItem).count,1);
const previous=[...header.slice(0,5),...header.slice(6),'Image link'];
const oldImage=['vocab',1,1,1,'imageWord','book','كتاب','This book is new.',...Array(11).fill(''),'https://liplip.pages.dev/images/book.svg'];
assert.equal(I.parseRows([previous,oldImage],Z.validateItem).count,1);
assert.throws(()=>Z.validateItem('vocab',{type:'imageWord',en:'book',ar:'كتاب',example:'This book is new.',image:'javascript:alert(1)'}),/رابط الصورة/);
Z.start(1);
assert.match(Z.render({snapshot:{}}),/replay-word/);
Z.afterRender();Z.afterRender();assert.equal(spoken.length,1);
assert.match(Z.render({snapshot:{}}),/zone-flash/);
console.log('Image types, HTTPS validation, old template compatibility, and once-only word playback passed');
