const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'..');
const events={},sessions=new Map(),drafts=new Map();
let editorForm=null;
const app={innerHTML:'',addEventListener:(name,fn)=>events[name]=fn};
const storage=map=>({getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)});
const context={document:{getElementById:id=>id==='app'?app:id==='zone-item-form'?editorForm:{textContent:''}},window:{scrollTo(){}},sessionStorage:storage(sessions),localStorage:storage(drafts),FormData:class{constructor(form){this.values=form.values||{}}get(k){return this.values[k]}has(k){return Object.hasOwn(this.values,k)}[Symbol.iterator](){return Object.entries(this.values)[Symbol.iterator]()}},Date,Number,String,Object,Set,Math};
vm.createContext(context);
for(const name of ['progress.js','content.js','zone.js'])vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),context);
vm.runInContext('this.P=LiplipProgress;this.Z=LiplipZone;',context);
vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),context);
const P=context.P,Z=context.Z;
function click(key,value,extra={}){const prop=key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());events.click({target:{closest:selector=>selector===`[data-${key}]`?{dataset:{[prop]:value,...extra}}:null},preventDefault(){}})}
function submit(id,values={}){events.submit({target:{id,values,reportValidity:()=>true},preventDefault(){}})}
async function main(){
click('action','auth');click('action','signin');click('action','guest');click('nav','الدراسة');click('action','study-box');
assert.match(app.innerHTML,/كلمة جديدة، مساحة أكبر/);
assert.match(app.innerHTML,/zone-simple-nav/);
assert.ok(!app.innerHTML.includes('data-zone="advance"'),'Vocabulary has no separate advance control');
assert.ok(!app.innerHTML.includes('data-zone="audio"'),'Vocabulary card controls are previous and next only');
assert.ok(!app.innerHTML.includes('class="mainnav"'),'Zone removes main navigation');
assert.ok(!app.innerHTML.includes('class="topbar"'),'Zone replaces site header');
assert.equal(P.snapshot(JSON.parse(sessions.get('liplip-preview')).progress).vocabularyCount,0);
let heard=null;context.window.speechSynthesis={cancel(){},speak:u=>heard=u};context.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};
click('zone','flip');assert.match(app.innerHTML,/مرحباً/);
click('zone','next');click('zone','exit');assert.match(app.innerHTML,/افتح درس الصندوق/);
click('action','study-box');assert.match(app.innerHTML,/البطاقة 2 من 5/,'Exit resumes current card');
for(let i=1;i<5;i++){click('zone','flip');click('zone','next')}
assert.match(app.innerHTML,/هل استقرّت الكلمات/,'Last next opens the vocabulary check');
submit('zone-quiz-form',{cv1:'2',cv2:'2'});assert.match(app.innerHTML,/تحتاج 70%/);
submit('zone-quiz-form',{cv1:'0',cv2:'1'});assert.match(app.innerHTML,/اسمع ثم سجّل صوتك/);
assert.match(app.innerHTML,/zone-pronounce-pair/);
assert.match(app.innerHTML,/zone-hear/);
assert.match(app.innerHTML,/zone-say/);
assert.ok(!app.innerHTML.includes('data-zone="advance"'),'Listening has no separate advance control');
click('zone','audio',{index:'0'});assert.equal(heard.text,'hello');assert.equal(heard.lang,'en-US');
let streamsStopped=0, permissionRequests=0;
context.navigator={mediaDevices:{getUserMedia:async()=>{permissionRequests++;return {getTracks:()=>[{stop:()=>streamsStopped++}]}}}};
context.Blob=Blob;
context.MediaRecorder=class {constructor(){this.state='inactive';this.mimeType='audio/webm'}start(){this.state='recording'}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['test voice'])});this.onstop?.()}};
for(let i=0;i<4;i++){
 click('zone','mic',{index:String(i)});await new Promise(resolve=>setImmediate(resolve));
 assert.match(app.innerHTML,/aria-pressed="true"/,'Mic tile is actively recording');
 assert.match(app.innerHTML,/data-zone="next" class="zone-primary" disabled/,'Next stays locked while recording');
 click('zone','mic',{index:String(i)});
 assert.match(app.innerHTML,/aria-pressed="false"/,'Second tap stops recording');
 if(i===0){click('zone','mic',{index:'0'});await new Promise(resolve=>setImmediate(resolve));assert.match(app.innerHTML,/data-zone="next" class="zone-primary" disabled/,'Retake locks Next');click('zone','mic',{index:'0'})}
 click('zone','next');
}
assert.equal(permissionRequests,5);
assert.equal(streamsStopped,5);
assert.equal(JSON.parse(drafts.get('liplip-zone-state-v1')).spoken[0].method,'recorded');
assert.ok(!drafts.get('liplip-zone-state-v1').includes('test voice'),'Raw audio is not persisted');
assert.match(app.innerHTML,/هل سمعت المعنى/,'Last next opens listening check');
assert.match(app.innerHTML,/class="zone-question-play /,'Listening questions have a dedicated player');
assert.match(app.innerHTML,/استمع إلى السؤال/);
click('zone','audio-question',{process:'checkpointListen',index:'0'});
assert.equal(heard.text,'hello');
assert.match(app.innerHTML,/aria-pressed="true"/);
heard.onend();assert.match(app.innerHTML,/aria-pressed="false"/);
click('zone','audio-question',{process:'checkpointListen',index:'1'});
assert.equal(heard.text,'goodbye');
click('zone','audio-question',{process:'checkpointListen',index:'1'});
assert.match(app.innerHTML,/aria-pressed="false"/);
submit('zone-quiz-form',{cl1:'0',cl2:'1'});assert.match(app.innerHTML,/التحية والسؤال عن الحال/);
assert.match(app.innerHTML,/بناء الجملة/);submit('zone-quiz-form',{gt:'0'});
assert.match(app.innerHTML,/أثبت ما تعلّمته/);
submit('zone-quiz-form',{e1:'1',e2:'0',e3:'hello'});
assert.match(app.innerHTML,/تم إنجاز الصندوق/);
let progress=JSON.parse(sessions.get('liplip-preview')).progress;
assert.equal(P.snapshot(progress).currentBox,2);
assert.equal(P.snapshot(progress).vocabularyCount,4);
assert.equal(progress.grammar.length,2,'Completed box saves its sentence and question rules');
assert.equal(progress.vocabulary[0].ar,'مرحباً','Learned words retain their translation');
assert.equal(P.snapshot(progress).metrics.pronunciation.average,0,'Manual repetition is not a measured pronunciation rating');
assert.equal(P.snapshot(progress).metrics.writing.average,100);
assert.ok(!drafts.has('liplip-zone-state-v1'),'Completed zone state cleared');
click('action','next-lesson');
click('zone','control');assert.match(app.innerHTML,/إدارة المحتوى/);
click('zone','menu-add');click('zone','process',{value:'vocab'});click('zone','type',{value:'sentence'});click('zone','add-form');
editorForm={values:{en:'I am ready.',ar:'أنا مستعد.',example:'I am ready to learn.'}};submit('zone-item-form');
assert.equal(Z.getContent(2).vocab.length,6);
assert.ok(drafts.has('liplip-zone-content-v1'));
click('zone','menu-edit');submit('zone-jump-form',{stage:'1',step:'1',box:'2'});
assert.match(app.innerHTML,/I am ready/);
const added=Z.getContent(2).vocab.at(-1);
click('zone','select-item',{process:'vocab',id:added.id});
editorForm={values:{en:'I am prepared.',ar:'أنا جاهز.',example:'I am prepared now.'}};submit('zone-item-form');
assert.equal(Z.getContent(2).vocab.at(-1).en,'I am prepared.');
click('zone','select-item',{process:'vocab',id:added.id});click('zone','delete-item');assert.match(app.innerHTML,/هل تريد حذف/);
click('zone','confirm-delete');assert.equal(Z.getContent(2).vocab.length,5);
const grammarRule=Z.getContent(2).grammar.find(x=>x.type==='sentenceRule');
click('zone','select-item',{process:'grammar',id:grammarRule.id});
editorForm={values:{title:'التعريف بالنفس باستخدام I am',formula:grammarRule.formula,body:grammarRule.body,example:grammarRule.example}};
submit('zone-item-form');
drafts.set('liplip-zone-state-v1',JSON.stringify({boxId:2,phase:4,card:0,reviewed:[],spoken:{},answers:{},attempts:{}}));
Z.start(2);
assert.match(Z.render({snapshot:P.snapshot(JSON.parse(sessions.get('liplip-preview')).progress)}),/التعريف بالنفس باستخدام I am/,'Grammar heading follows editable box content');
drafts.set('liplip-zone-state-v1',JSON.stringify({boxId:2,phase:2,card:0,reviewed:[],spoken:{},answers:{},attempts:{}}));
Z.start(2);
click('zone','mic',{index:'0'});await new Promise(resolve=>setImmediate(resolve));
assert.match(app.innerHTML,/aria-pressed="true"/);
click('zone','exit');
assert.equal(streamsStopped,6,'Leaving closes the microphone stream');
click('action','study-box');
context.navigator.mediaDevices.getUserMedia=async()=>{throw Object.assign(new Error('blocked'),{name:'NotAllowedError'})};
drafts.set('liplip-zone-state-v1',JSON.stringify({boxId:2,phase:2,card:0,reviewed:[],spoken:{},answers:{},attempts:{}}));
Z.start(2);
click('zone','mic',{index:'0'});await new Promise(resolve=>setImmediate(resolve));
assert.match(app.innerHTML,/لم يُسمح باستخدام الميكروفون/);
assert.match(app.innerHTML,/data-zone="next" class="zone-primary" disabled/,'Denied permission does not unlock Next');
let grantPermission;
context.navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{grantPermission=resolve});
click('zone','mic',{index:'0'});
click('zone','exit');
grantPermission({getTracks:()=>[{stop:()=>streamsStopped++}]});
await new Promise(resolve=>setImmediate(resolve));
assert.equal(streamsStopped,7,'A late permission grant is closed after exit');
assert.throws(()=>Z.validateItem('listen',{type:'word',en:'',ar:'x'}),/أكمل الحقول/);
console.log('Focused zone, recording toggle, resume, checks, completion, and content CRUD passed');
}
main().catch(error=>{console.error(error);process.exitCode=1});
