const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'..');
const events={},sessions=new Map(),drafts=new Map();
let editorForm=null;
const app={innerHTML:'',addEventListener:(name,fn)=>events[name]=fn};
const storage=map=>({getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)});
const context={document:{getElementById:id=>id==='app'?app:id==='zone-item-form'?editorForm:{textContent:''}},window:{scrollTo(){}},sessionStorage:storage(sessions),localStorage:storage(drafts),FormData:class{constructor(form){this.values=form.values||{}}get(k){return this.values[k]}has(k){return Object.hasOwn(this.values,k)}[Symbol.iterator](){return Object.entries(this.values)[Symbol.iterator]()}},Date,Number,String,Object,Set,Math};
vm.createContext(context);
for(const name of ['progress.js','content.js','zone.js'])vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),context);
vm.runInContext('this.P=LiplipProgress;this.Z=LiplipZone;',context);
vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),context);
const P=context.P,Z=context.Z;
function click(key,value,extra={}){const prop=key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());events.click({target:{closest:selector=>selector===`[data-${key}]`?{dataset:{[prop]:value,...extra}}:null},preventDefault(){}})}
function submit(id,values={}){events.submit({target:{id,values,reportValidity:()=>true},preventDefault(){}})}
click('action','auth');click('action','signin');click('action','guest');click('nav','الدراسة');click('action','study-box');
assert.match(app.innerHTML,/كلمة جديدة، مساحة أكبر/);
assert.ok(!app.innerHTML.includes('class="mainnav"'),'Zone removes main navigation');
assert.ok(!app.innerHTML.includes('class="topbar"'),'Zone replaces site header');
assert.equal(P.snapshot(JSON.parse(sessions.get('liplip-preview')).progress).vocabularyCount,0);
click('zone','audio',{index:'0'});assert.match(app.innerHTML,/الصوت غير متاح/);
let heard=null;context.window.speechSynthesis={cancel(){},speak:u=>heard=u};context.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};
click('zone','audio',{index:'0'});assert.equal(heard.text,'hello');assert.equal(heard.lang,'en-US');
click('zone','flip');assert.match(app.innerHTML,/مرحباً/);
click('zone','next');click('zone','exit');assert.match(app.innerHTML,/افتح درس الصندوق/);
click('action','study-box');assert.match(app.innerHTML,/البطاقة 2 من 5/,'Exit resumes current card');
for(let i=1;i<5;i++){click('zone','flip');click('zone','next')}
click('zone','advance');assert.match(app.innerHTML,/هل استقرّت الكلمات/);
submit('zone-quiz-form',{cv1:'2',cv2:'2'});assert.match(app.innerHTML,/تحتاج 70%/);
submit('zone-quiz-form',{cv1:'0',cv2:'1'});assert.match(app.innerHTML,/اسمعها/);
click('zone','mic',{index:'0'});assert.match(app.innerHTML,/غير مدعوم/);
for(let i=0;i<4;i++){click('zone','manual',{index:String(i)});if(i<3)click('zone','next')}
click('zone','advance');assert.match(app.innerHTML,/هل سمعت المعنى/);
submit('zone-quiz-form',{cl1:'0',cl2:'1'});assert.match(app.innerHTML,/ابنِ الجملة/);
assert.match(app.innerHTML,/قانون الجملة/);submit('zone-quiz-form',{gt:'0'});
assert.match(app.innerHTML,/أثبت ما تعلّمته/);
submit('zone-quiz-form',{e1:'1',e2:'0',e3:'hello'});
assert.match(app.innerHTML,/تم إنجاز الصندوق/);
let progress=JSON.parse(sessions.get('liplip-preview')).progress;
assert.equal(P.snapshot(progress).currentBox,2);
assert.equal(P.snapshot(progress).vocabularyCount,4);
assert.equal(P.snapshot(progress).metrics.pronunciation.average,0,'Manual repetition is not a measured pronunciation rating');
assert.equal(P.snapshot(progress).metrics.writing.average,100);
assert.ok(!drafts.has('liplip-zone-state-v1'),'Completed zone state cleared');
click('action','next-lesson');
click('zone','control');assert.match(app.innerHTML,/إدارة المحتوى/);
click('zone','menu-add');click('zone','process',{value:'vocab'});click('zone','type',{value:'sentence'});click('zone','add-form');
editorForm={values:{en:'I am ready.',ar:'أنا مستعد.',example:'I am ready to learn.'}};submit('zone-item-form');
assert.equal(Z.getContent(2).vocab.length,6);
assert.ok(drafts.has('liplip-zone-content-v1'));
click('zone','menu-edit');submit('zone-jump-form',{stage:'1',step:'1',box:'2'});
assert.match(app.innerHTML,/I am ready/);
const added=Z.getContent(2).vocab.at(-1);
click('zone','select-item',{process:'vocab',id:added.id});
editorForm={values:{en:'I am prepared.',ar:'أنا جاهز.',example:'I am prepared now.'}};submit('zone-item-form');
assert.equal(Z.getContent(2).vocab.at(-1).en,'I am prepared.');
click('zone','select-item',{process:'vocab',id:added.id});click('zone','delete-item');assert.match(app.innerHTML,/هل تريد حذف/);
click('zone','confirm-delete');assert.equal(Z.getContent(2).vocab.length,5);
assert.throws(()=>Z.validateItem('listen',{type:'word',en:'',ar:'x'}),/أكمل الحقول/);
console.log('Focused zone, resume, checks, completion, and content CRUD passed');
