const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..');
const context={console,URL,Blob,Uint8Array,setTimeout,document:undefined,MutationObserver:undefined,JSZip:undefined,DOMParser:undefined};
context.LiplipReceptionImporter={parseRows(){throw Error('legacy')}};
context.LiplipReception={downloadTemplate(){},validate(process,item){const allowed={watch:['video'],watchExam:['textVoice','imageArabicWrite','mcq'],read:['storyPage'],readExam:['enToArWrite','arToEnWrite','mcq']};assert.ok(allowed[process]?.includes(item.type));if(process==='watch')assert.ok(item.youtube&&item.title);if(process==='read')assert.ok(item.english&&item.title);if(item.type==='textVoice')assert.ok(item.english&&item.options.length>=2&&Number.isInteger(item.correct));if(item.type==='imageArabicWrite')assert.ok(item.image&&item.answer);if(item.type==='mcq')assert.ok(item.prompt&&item.options.length>=2&&Number.isInteger(item.correct));if(item.type==='enToArWrite')assert.ok(item.english&&item.answer);if(item.type==='arToEnWrite')assert.ok(item.arabic&&item.answer);return {...item}}};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'reception-template-v18.js'),'utf8'),context);
const H=context.LiplipReceptionImporter.TABLE_HEADERS;assert.equal(H.length,31);assert.deepEqual([...H.slice(0,5)],['Level','Step','Box','Video link','Story text']);
const rows=[H,[1,2,3,'https://www.youtube.com/watch?v=abc','Story one','فيديو','قصة',1,'https://example.com/story.jpg','textVoice','استمع','Hello','','Hello','Bye','','',1,'','شرح','enToArWrite','ترجم','red','','','','','','','أحمر','شرح'],[1,2,3,'','Story two','','',2,'','imageArabicWrite','اكتب','','https://example.com/cat.jpg','','','','','','قطة','شرح','arToEnWrite','اكتب','','كرة','','','','','','ball','شرح'],[1,2,3,'','','','','','','mcq','اختر','','','نعم','لا','','',1,'','شرح','mcq','اختر','','','Tom','Sara','','',1,'','شرح']];
const result=context.LiplipReceptionImporter.parseRows(rows,context.LiplipReception.validate),id=23,b=result.boxes.get(id);assert.ok(b);assert.equal(b.watch.length,1);assert.equal(b.read.length,2);assert.deepEqual(b.watchExam.map(x=>x.type),['textVoice','imageArabicWrite','mcq']);assert.deepEqual(b.readExam.map(x=>x.type),['enToArWrite','arToEnWrite','mcq']);console.log('Structured Watch/Read Excel v18 passed');
