const app = document.getElementById('app');
const cities = ['بغداد','البصرة','نينوى','أربيل','السليمانية','دهوك','كركوك','الأنبار','بابل','ديالى','ذي قار','ميسان','المثنى','النجف','كربلاء','القادسية','صلاح الدين','واسط','حلبجة'];
const sections = [
  {name:'الرئيسية',icon:'home'}, {name:'الدراسة',icon:'book'},
  {name:'خزانتي',icon:'closet'}, {name:'تحدّث',icon:'chat'}, {name:'الإعدادات',icon:'settings'}
];
const paths = {
  arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',
  back:'<path d="M19 12H5m6 6-6-6 6-6"/>',
  home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z"/><path d="M9 21v-7h6v7"/>',
  book:'<path d="M12 7c-2-2-5-2-9-2v15c4 0 7 0 9 2 2-2 5-2 9-2V5c-4 0-7 0-9 2Zm0 0v15"/>',
  closet:'<path d="m8 4 2 2h4l2-2 4 3-2 5-2-1v10H8V11l-2 1-2-5 4-3Z"/>',
  chat:'<path d="M20 11.5a7.5 7.5 0 0 1-7.5 7.5 8 8 0 0 1-3-.6L4 20l1.6-5.2a7.5 7.5 0 1 1 14.4-3.3Z"/><path d="M9 11.5h.01m3.5 0h.01m3.5 0h.01"/>',
  settings:'<path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/><path d="M19 13.5 21 12l-2-1.5-.4-2.1-2.4-.4L15 5l-3-1-3 1-1.2 3-2.4.4L5 10.5 3 12l2 1.5.4 2.1 2.4.4L9 19l3 1 3-1 1.2-3 2.4-.4.4-2.1Z"/>',
  spark:'<path d="m12 2 1.9 6.1L20 10l-6.1 1.9L12 18l-1.9-6.1L4 10l6.1-1.9L12 2Zm7 15 .7 1.3L21 19l-1.3.7L19 21l-.7-1.3L17 19l1.3-.7L19 17Z"/>',
  globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c-3 3-3 15 0 18m0-18c3 3 3 15 0 18"/>',
  compass:'<circle cx="12" cy="12" r="9"/><path d="m15 9-2 4-4 2 2-4 4-2Z"/>',
  heart:'<path d="M20.8 8.6c0 4.7-8.8 10.4-8.8 10.4S3.2 13.3 3.2 8.6a4.6 4.6 0 0 1 8.8-1.7 4.6 4.6 0 0 1 8.8 1.7Z"/>',
  bolt:'<path d="m13 2-9 11h7l-1 9 10-12h-7V2Z"/>',
  user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
  logout:'<path d="M10 4H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h5m4-4 4-4-4-4m4 4H9"/>',
  google:'<path d="M20 12a8 8 0 1 1-2.3-5.7M20 12h-8m8 0c0 4.7-3.2 8-8 8"/>',
  facebook:'<path d="M14 21v-9h3l.5-4H14V6.5c0-1 .4-1.5 1.5-1.5H18V2h-3c-3.5 0-5 1.7-5 4.5V8H7v4h3v9"/>',
  phone:'<path d="M5 3h4l1 4-2 2a13 13 0 0 0 7 7l2-2 4 1v4a2 2 0 0 1-2 2C10 21 3 14 3 5a2 2 0 0 1 2-2Z"/>',
  lock:'<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>'
};
function icon(name, size=22){return `<svg aria-hidden="true" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.spark}</svg>`}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const state={page:'landing',nav:'الرئيسية',mode:'signup',profile:null,guest:false,testAnswers:{},message:''};
try {const saved=JSON.parse(sessionStorage.getItem('liplip-preview')||'null');if(saved&&typeof saved==='object'){if(saved.profile&&typeof saved.profile.name==='string')state.profile=saved.profile;state.guest=saved.guest===true;if(state.profile||state.guest)state.page='app'}}catch{}
function save(){try{sessionStorage.setItem('liplip-preview',JSON.stringify({profile:state.profile,guest:state.guest}))}catch{}}
function logo(){return `<a href="#" class="logo" data-action="landing" aria-label="liplip، الصفحة الأولى"><span>li</span><span>p</span><span>li</span><span>p</span><i></i></a>`}
function header(){return `<header class="topbar">${logo()}<div class="top-actions"><span class="header-note">من العراق، إلى العالم</span>${state.page==='app'?`<button class="header-button" data-action="logout">${icon('logout',18)} <span>خروج</span></button>`:state.page==='landing'?`<button class="header-button" data-action="auth">تسجيل الدخول ${icon('arrow',18)}</button>`:''}</div></header>`}
function landing(){return `<main class="landing"><section class="hero wrap"><div class="hero-copy"><span class="eyebrow">${icon('spark',16)} مساحة جديدة لتعلّم اللغات</span><h1>كل كلمة،<br><em>تفتح لك عالماً.</em></h1><p>تعلّم بطريقتك، واكتشف فرصاً أبعد مما تتخيّل. رحلتك مع اللغات تبدأ من هنا، أينما كنت في العراق.</p><div class="hero-actions"><button class="cta" data-action="auth">انضم إلى liplip ${icon('arrow',21)}</button><span class="aside-note">خطوتك الأولى بسيطة وممتعة</span></div><div class="hero-foot"><span class="tiny-mark">${icon('check',15)}</span> فضولك كافٍ لتبدأ</div></div><div class="hero-art" role="img" aria-label="رسم تجريدي لفقاعة حوار وكلمات بلغات مختلفة"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-blob"></div><div class="art-main"><div class="art-icon">${icon('chat',100)}</div><div class="art-line"></div><div class="art-line short"></div><strong>مرحباً بالعالم</strong></div><div class="word-card word-one"><span class="word-dot pink"></span> Hello!</div><div class="word-card word-two"><span class="word-dot mint"></span> أهلاً وسهلاً</div><div class="word-card word-three"><span class="word-dot gold"></span> Bonjour!</div><span class="art-spark spark-one">${icon('spark',43)}</span><span class="art-spark spark-two">${icon('spark',27)}</span></div></section><div class="marquee"><div class="wrap marquee-inner"><span>${icon('globe',23)} من العراق، إلى كل مكان</span><i></i><span>${icon('heart',23)} تعلّم على راحتك</span><i></i><span>${icon('spark',23)} بداية صغيرة، عالم كبير</span></div></div><section class="features wrap"><span class="section-kicker">رحلة على مقاسك</span><h2>البداية الحلوة من هنا.</h2><p class="section-lead">مكان يشجّعك على المحاولة، ويفتح لك باباً جديداً كل يوم.</p><div class="feature-grid"><article class="feature feature-lilac"><div class="feature-icon">${icon('compass',31)}</div><span class="feature-number">01</span><h3>امشِ بخطاك</h3><p>ابدأ من مستواك الحقيقي، وتقدّم بإيقاع يناسب يومك وحياتك.</p></article><article class="feature feature-peach"><div class="feature-icon">${icon('chat',31)}</div><span class="feature-number">02</span><h3>احكِ بثقة</h3><p>كل كلمة تتعلّمها تقرّبك من محادثة جديدة وفرصة أجمل.</p></article><article class="feature feature-mint"><div class="feature-icon">${icon('globe',31)}</div><span class="feature-number">03</span><h3>وسّع عالمك</h3><p>اللغات تفتح لك أبواب المعرفة، والناس، والأماكن البعيدة.</p></article></div></section><section class="end-banner wrap"><div><span class="section-kicker">جاهز للخطوة الأولى؟</span><h2>العالم ينتظر صوتك.</h2></div><button class="cta cta-light" data-action="auth">ابدأ رحلتك ${icon('arrow',20)}</button></section></main><footer class="footer"><div class="wrap"><span>© ${new Date().getFullYear()} liplip</span><span>صُنع بحبّ للفضوليين في العراق</span></div></footer>`}
function auth(){const signup=state.mode==='signup';return `<main class="auth-layout"><div class="auth-art"><div class="auth-art-content"><div class="auth-art-icon">${icon('globe',110)}</div><span class="section-kicker">liplip، مساحتك الجديدة</span><h2>خطوة صغيرة.<br>عالم من الاحتمالات.</h2><p>لكل حكاية كلمة أولى. خلّينا نبدأ حكايتك.</p><div class="auth-bubble bubble-a">أهلاً بك</div><div class="auth-bubble bubble-b">Let’s go</div></div></div><div class="auth-panel"><div class="form-card"><button class="back" data-action="landing">${icon('back',17)} العودة إلى البداية</button><span class="section-kicker">أهلاً بك في liplip</span><h1>${signup?'خلّينا نتعرّف.':'نورت من جديد.'}</h1><p class="muted">${signup?'أنشئ مساحتك وابدأ رحلتك بخطوات بسيطة.':'تابع رحلتك أو ادخل سريعاً كضيف.'}</p><div class="tabs" role="tablist" aria-label="نوع الدخول"><button role="tab" aria-selected="${signup}" class="${signup?'active':''}" data-action="signup">إنشاء حساب</button><button role="tab" aria-selected="${!signup}" class="${!signup?'active':''}" data-action="signin">تسجيل الدخول</button></div><form id="auth-form"><div class="field"><label for="email">البريد الإلكتروني</label><input id="email" name="email" type="email" dir="ltr" placeholder="you@example.com" required autocomplete="email"></div><button class="cta full" type="submit">متابعة إلى التجربة ${icon('arrow',19)}</button></form>${!signup?`<button class="guest-button" data-action="guest">${icon('bolt',21)} دخول سريع كضيف <span>بدون تسجيل</span></button>`:''}<div class="divider"><span>أو باستخدام</span></div><div class="social"><button type="button" data-provider="Google">${icon('google',21)} Google</button><button type="button" data-provider="Facebook">${icon('facebook',21)} Facebook</button><button type="button" data-provider="WhatsApp">${icon('phone',21)} WhatsApp</button></div><p id="auth-message" class="notice ${state.message?'error':''}" role="status">${state.message?esc(state.message):'هذه نسخة تجريبية. لا يتم إنشاء حساب حقيقي، وخيارات الربط الخارجي قيد الإعداد.'}</p></div></div></main>`}
function ageFromBirth(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return null;const d=new Date(value+'T12:00:00');if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==value)return null;const now=new Date();let age=now.getFullYear()-d.getFullYear();if(now.getMonth()<d.getMonth()||(now.getMonth()===d.getMonth()&&now.getDate()<d.getDate()))age--;return age}
function profile(){const p=state.profile||{};const age=p.birth?ageFromBirth(p.birth):null;return `<main class="profile-shell"><div class="step-line"><span>خطوتك الأولى</span><span>01 / 02</span></div><div class="progress"><span style="width:50%"></span></div><span class="section-kicker">خلّينا نبدأ صح</span><h1>نحب نتعرّف عليك.</h1><p class="lead">بعض التفاصيل تساعدنا نجهّز مساحتك. في هذه النسخة التجريبية تبقى بياناتك داخل تبويب المتصفح فقط.</p><form id="profile-form"><div class="form-grid"><div class="field span-2"><label for="fullName">الاسم الكامل</label><input id="fullName" name="name" type="text" minlength="2" maxlength="80" autocomplete="name" required placeholder="بماذا تحب أن نناديك؟" value="${esc(p.name||'')}"></div><div class="field"><label for="birth">تاريخ الميلاد</label><input id="birth" name="birth" type="date" required max="${new Date().toISOString().slice(0,10)}" value="${esc(p.birth||'')}"><small id="age-display">${age===null?'سنحسب عمرك تلقائياً.':`العمر: ${age} سنة`}</small></div><div class="field"><label for="gender">الجنس</label><select id="gender" name="gender" required><option value="">اختر ما يناسبك</option>${['أنثى','ذكر','آخر','أفضل عدم الإفصاح'].map(v=>`<option ${p.gender===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="city">المحافظة في العراق</label><select id="city" name="city" required><option value="">اختر المحافظة</option>${cities.map(v=>`<option ${p.city===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="town">المدينة أو المنطقة</label><input id="town" name="town" type="text" maxlength="80" required placeholder="مثلاً: المنصور" value="${esc(p.town||'')}"></div><div class="field span-2"><label for="level">مستواك في اللغة الإنجليزية</label><select id="level" name="level" required><option value="">اختر مستواك</option><option value="a1" ${p.level==='a1'?'selected':''}>مبتدئ A1</option><option value="a2" ${p.level==='a2'?'selected':''}>أساسي A2</option><option value="b1" ${p.level==='b1'?'selected':''}>متوسط B1</option><option value="b2" ${p.level==='b2'?'selected':''}>فوق المتوسط B2</option><option value="c1" ${p.level==='c1'?'selected':''}>متقدم C1 أو أعلى</option><option value="unknown">لا أعرف — أريد اختباراً سريعاً</option></select><small>الاختبار السريع للتوجيه الأولي، وليس شهادة مستوى معتمدة.</small></div></div><p id="profile-error" class="notice error" role="alert"></p><button class="cta" type="submit">متابعة ${icon('arrow',19)}</button></form></main>`}
const questions=[
 {q:'Choose the correct greeting:',a:['Good morning!','Good mornings!','Morning good!'],right:0},
 {q:'She ___ to school every day.',a:['go','goes','going'],right:1},
 {q:'If it rains tomorrow, we ___ at home.',a:['stay','stayed','will stay'],right:2},
 {q:'Choose the closest meaning of “reliable”:',a:['Dependable','Interesting','Expensive'],right:0},
 {q:'By the time I arrived, they ___ dinner.',a:['finished','had finished','finish'],right:1}
];
function test(){return `<main class="profile-shell"><div class="step-line"><span>اختبار تحديد البداية</span><span>02 / 02</span></div><div class="progress"><span style="width:100%"></span></div><span class="section-kicker">بدون ضغط</span><h1>وين تحب تبدأ؟</h1><p class="lead">خمسة أسئلة بسيطة بالإنجليزية تعطينا فكرة تقريبية عن نقطة البداية. النتيجة ليست تقييماً معتمداً.</p><form id="test-form">${questions.map((q,i)=>`<fieldset class="question"><legend>${i+1}. <span dir="ltr">${esc(q.q)}</span></legend><div class="answers" dir="ltr">${q.a.map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}" required ${state.testAnswers[i]===j?'checked':''}>${esc(a)}</label>`).join('')}</div></fieldset>`).join('')}<button class="cta" type="submit">شوف نقطة بدايتك ${icon('arrow',19)}</button></form></main>`}
function nav(){return `<nav class="mainnav" aria-label="التنقّل الرئيسي">${sections.map(s=>`<button class="navitem ${state.nav===s.name?'active':''}" data-nav="${s.name}" ${state.nav===s.name?'aria-current="page"':''}>${icon(s.icon,22)}<span>${s.name}</span></button>`).join('')}</nav>`}
function levelLabel(value){const map={a1:'مبتدئ A1',a2:'أساسي A2',b1:'متوسط B1',b2:'فوق المتوسط B2',c1:'متقدم C1+',starter:'بداية مقترحة: مبتدئ',elementary:'بداية مقترحة: أساسي',intermediate:'بداية مقترحة: متوسط'};return map[value]||value||'مستكشف'}
function dashboard(){const first=state.guest?'ضيفنا':(state.profile?.name||'صديقنا').trim().split(/\s+/)[0];const level=state.guest?'تصفّح كضيف':levelLabel(state.profile?.level);return `<main class="dashboard"><div class="dash-intro"><div><span class="section-kicker">مساحتك الخاصة</span><h1>هلا ${esc(first)}، نورت!</h1><p>كل يوم فرصة جديدة لتكتشف كلمة، وفكرة، وعالماً.</p></div><span class="badge">${icon(state.guest?'user':'spark',17)} ${esc(level)}</span></div><div class="welcome-card"><div class="welcome-text"><span class="section-kicker">أهلاً بك في liplip</span><h2>هذه بداية حكايتك.</h2><p>سعداء بوجودك معنا. نجهّز لك مساحة للتعلّم والتجربة والتواصل، خطوة وراء خطوة.</p>${state.guest?`<button class="text-link" data-action="auth">أنشئ حساباً لتكمل رحلتك ${icon('arrow',17)}</button>`:''}</div><div class="welcome-art" aria-hidden="true"><div class="welcome-orbit"></div><span>${icon('globe',106)}</span><i>${icon('spark',31)}</i></div></div><div class="dashboard-grid"><article><div class="tile-icon lilac">${icon('compass',27)}</div><h3>رحلتك على طريقتك</h3><p>ابدأ من فضولك، واستعد لاكتشاف لغات وأفكار جديدة.</p></article><article><div class="tile-icon peach">${icon('bolt',27)}</div><h3>قريباً المزيد</h3><p>مساحات الدراسة والخزانة والتحدّث والإعدادات في الطريق.</p></article></div></main>`}
function coming(){const s=sections.find(x=>x.name===state.nav)||sections[1];return `<main class="coming"><div class="coming-inner"><div class="coming-icon">${icon(s.icon,58)}</div><span class="section-kicker">${esc(s.name)}</span><h1>شيء حلو بالطريق.</h1><p>نعمل على تجهيز هذه المساحة بعناية. ترقّب طرقاً جديدة للتعلّم والتواصل قريباً.</p><button class="cta" data-nav="الرئيسية">ارجع للرئيسية ${icon('arrow',19)}</button></div></main>`}
function render(){app.innerHTML=header()+(state.page==='landing'?landing():state.page==='auth'?auth():state.page==='profile'?profile():state.page==='test'?test():`<div class="app-layout">${nav()}${state.nav==='الرئيسية'?dashboard():coming()}</div>`);window.scrollTo(0,0)}
app.addEventListener('click',e=>{
 const provider=e.target.closest('[data-provider]');if(provider){document.getElementById('auth-message').textContent=`الدخول عبر ${provider.dataset.provider} غير مفعّل في النسخة التجريبية. يلزم ربط مزوّد الحسابات بخادم آمن.`;return}
 const navButton=e.target.closest('[data-nav]');if(navButton){state.nav=navButton.dataset.nav;render();return}
 const button=e.target.closest('[data-action]');if(!button)return;e.preventDefault();const action=button.dataset.action;
 if(action==='landing')state.page='landing';
 else if(action==='auth'){state.page='auth';state.message=''}
 else if(action==='signup'||action==='signin'){state.mode=action;state.message=''}
 else if(action==='guest'){state.guest=true;state.profile=null;state.nav='الرئيسية';state.page='app';save()}
 else if(action==='logout'){state.profile=null;state.guest=false;sessionStorage.removeItem('liplip-preview');state.page='landing';state.nav='الرئيسية'}
 render();
});
app.addEventListener('input',e=>{if(e.target.id==='birth'){const age=ageFromBirth(e.target.value);document.getElementById('age-display').textContent=age===null?'سنحسب عمرك تلقائياً.':`العمر: ${age} سنة`}});
app.addEventListener('submit',e=>{
 e.preventDefault();if(!e.target.reportValidity())return;
 if(e.target.id==='auth-form'){state.guest=false;state.page=state.profile?'app':'profile';render();return}
 if(e.target.id==='profile-form'){const data=Object.fromEntries(new FormData(e.target));const age=ageFromBirth(data.birth);if(age===null||age<0||age>120){document.getElementById('profile-error').textContent='يرجى إدخال تاريخ ميلاد صحيح.';return}state.profile={...data,age};if(data.level==='unknown'){state.page='test'}else{save();state.page='app'}render();return}
 if(e.target.id==='test-form'){const data=new FormData(e.target);let score=0;questions.forEach((q,i)=>{const answer=Number(data.get(`q${i}`));state.testAnswers[i]=answer;if(answer===q.right)score++});state.profile.level=score<=1?'starter':score<=3?'elementary':'intermediate';state.page='app';save();render()}
});
render();
