/* Unified Study course: level -> box -> vocabulary, grammar, watch & read. */
const LiplipCourse = (() => {
  const PHASES = [
    {key:'vocabulary',label:'المفردات',short:'كلمات وصور وأصوات',processes:['content','exam']},
    {key:'grammar',label:'القواعد',short:'شرح وتطبيق',processes:['article','exam']},
    {key:'watchRead',label:'شاهد واقرأ',short:'فيديو وقصة',processes:['video','story']}
  ];
  const PHASE_FILE = {vocabulary:'liplip-vocabulary.xlsx',grammar:'liplip-grammar.xlsx',watchRead:'liplip-watch-read.xlsx'};
  const PHASE_VALUE = {vocabulary:'vocabulary',grammar:'grammar',watchRead:'watch&read'};
  const STORE_KEY='liplip-course-content-v2';
  const LEVEL_BOXES=200;
  let edits={};
  try{const raw=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');if(raw&&typeof raw==='object')edits=raw}catch{}
  let ui={view:'levels',level:null,boxId:null,phase:null,review:false,results:false,control:false,notice:'',error:'',storyPage:0,processView:0};

  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v??'').trim().toLocaleLowerCase().replace(/[\s\u064B-\u065F]+/g,' ');
  const location=id=>LiplipProgress.courseLocation(id);
  const globalId=(level,box)=>(level-1)*LEVEL_BOXES+box;
  const phaseDef=key=>PHASES.find(x=>x.key===key)||PHASES[0];
  const icon=(path,size=20)=>`<svg aria-hidden="true" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${path}</svg>`;
  const icons={back:'<path d="M19 12H5m6 6-6-6 6-6"/>',lock:'<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',check:'<path d="m5 12 4 4L19 6"/>',book:'<path d="M4 5c4 0 6 1 8 3 2-2 4-3 8-3v14c-4 0-6 1-8 3-2-2-4-3-8-3V5Z"/>',play:'<path d="m8 5 11 7-11 7V5Z"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 13.5 21 12l-2-1.5-.4-2.1-2.4-.4L15 5l-3-1-3 1-1.2 3-2.4.4L5 10.5 3 12l2 1.5.4 2.1 2.4.4L9 19l3 1 3-1 1.2-3 2.4-.4.4-2.1Z"/>'};

  function defaultContent(id){
    const loc=location(id),n=loc.box;
    return {
      vocabulary:{items:[
        {type:'word',order:1,en:`word ${n}`,ar:`كلمة ${n}`,voice:`word ${n}`},
        {type:'sentence',order:2,en:`This is example sentence ${n}.`,ar:'جملة تدريبية بسيطة.',voice:`This is example sentence ${n}.`}
      ],questions:[{type:'mcq',prompt:`اختر معنى word ${n}`,options:[`كلمة ${n}`,'جملة','صورة','قصة'],correct:0,answer:`كلمة ${n}`,explanation:'راجع بطاقة الكلمة.'}]},
      grammar:{article:{title:`قاعدة الصندوق ${n}`,rule:'استخدم ترتيب الجملة الواضح: فاعل ثم فعل ثم مفعول به.',normal:'Subject + verb + object.',negative:'Subject + do/does not + base verb + object.',question:'Do/Does + subject + base verb + object?',notes:['يتغير does مع he / she / it.','بعد do أو does يعود الفعل إلى صورته الأساسية.'],examples:Array.from({length:10},(_,i)=>({text:`Example ${i+1}: I use the word in a clear sentence.`,difficulty:i<4?'easy':i<8?'medium':'difficult'}))},questions:[{type:'mcq',prompt:'اختر ترتيب الجملة العادية.',options:['Subject + verb + object','Verb + subject + object','Object + verb + subject','Do + object'],correct:0,answer:'Subject + verb + object',explanation:'الجملة العادية تبدأ بالفاعل.'}]},
      watchRead:{video:{title:`فيديو الصندوق ${n}`,youtube:'dQw4w9WgXcQ'},videoQuestions:[{type:'mcq',prompt:'ما الفكرة الأساسية؟',options:['الفكرة الأولى','الفكرة الثانية','الفكرة الثالثة','الفكرة الرابعة'],correct:0,answer:'الفكرة الأولى',explanation:'شاهد المقطع مرة أخرى.'}],story:[{order:1,title:`قصة الصندوق ${n}`,text:`This is a short story for box ${n}. Read it carefully and notice the new vocabulary.`,arabic:'اقرأ القصة ولاحظ المفردات الجديدة.',image:''}],storyQuestions:[{type:'mcq',prompt:'ماذا قرأت؟',options:['قصة قصيرة','رسالة','إعلان','قائمة'],correct:0,answer:'قصة قصيرة',explanation:'النص قصة قصيرة.'}]}
    };
  }
  function cleanContent(value,id){
    const base=defaultContent(id),out=value&&typeof value==='object'?value:{};
    for(const key of ['vocabulary','grammar','watchRead'])if(!out[key]||typeof out[key]!=='object')out[key]=base[key];
    return out;
  }
  function getContent(id){return cleanContent(structuredClone(edits[String(id)]||defaultContent(id)),id)}
  function storeBox(id,content){const next=structuredClone(edits);next[String(id)]=content;localStorage.setItem(STORE_KEY,JSON.stringify(next));edits=next}

  function model(progress){
    const snap=LiplipProgress.courseSnapshot(progress),records=new Map(snap.records.map(x=>[x.boxId,x]));
    const phaseCount=id=>records.get(id)?.completedPhases?.length||0;
    const statusBox=id=>snap.completedBoxes.includes(id)?'complete':id===snap.currentBox?'current':'locked';
    const levelStat=level=>{const ids=Array.from({length:LEVEL_BOXES},(_,i)=>globalId(level,i+1)),complete=ids.filter(id=>statusBox(id)==='complete').length,units=ids.reduce((sum,id)=>sum+phaseCount(id),0);return {complete,percent:Math.round(units/(LEVEL_BOXES*3)*100)}};
    const currentLevel=snap.currentBox?location(snap.currentBox).level:5;
    const statusLevel=level=>snap.currentBox===null||level<currentLevel?'complete':level===currentLevel?'current':'locked';
    return {snap,records,phaseCount,statusBox,levelStat,currentLevel,statusLevel};
  }
  function phaseClass(count,status){if(status==='complete')return 'phase-3';return `phase-${Math.max(0,Math.min(2,count))}`}
  function chest(status){return `<span class="course-chest ${status}">${icon(status==='locked'?icons.lock:status==='complete'?icons.check:icons.book,18)}</span>`}
  function progressBar(percent){return `<span class="course-progress"><i style="width:${percent}%"></i></span>`}
  function levelsMap(m){return `<section class="course-map-panel"><div class="course-map-title"><div><span>ابدأ من هنا</span><h2>اختر المستوى</h2><p>كل مستوى يحتوي ٢٠٠ صندوق؛ لون الصندوق يوضح المرحلة التي وصل إليها.</p></div><strong>٥ مستويات</strong></div><div class="course-levels">${Array.from({length:5},(_,i)=>{const level=i+1,s=m.statusLevel(level),stat=m.levelStat(level);return `<button class="course-level ${s}" ${s==='locked'?'disabled':`data-course="level" data-level="${level}"`}><span>0${level}</span>${chest(s)}<div><small>المستوى ${level}</small><strong>${safe(LiplipProgress.STAGES[i])}</strong><p>${s==='locked'?'يفتح بعد إنهاء المستوى السابق':`${stat.complete} / ${LEVEL_BOXES} صندوق مكتمل`}</p>${progressBar(stat.percent)}</div><b>${stat.percent}%</b></button>`}).join('')}</div></section>`}
  function boxesMap(m,level){return `<section class="course-map-panel"><div class="course-breadcrumb"><button data-course="levels">${icon(icons.back,17)} المستويات</button><span>المستوى ${level} · ${safe(LiplipProgress.STAGES[level-1])}</span></div><div class="course-boxes">${Array.from({length:LEVEL_BOXES},(_,i)=>{const box=i+1,id=globalId(level,box),s=m.statusBox(id),count=m.phaseCount(id),record=m.records.get(id),phase=s==='complete'?3:count,label=s==='locked'?'مغلق':s==='complete'?'مراجعة':`${phaseDef(record?.currentPhase||m.snap.phase).label} · ${record?.processIndex===1?'العملية الثانية':'العملية الأولى'}`;return `<button class="course-box ${s} ${phaseClass(count,s)}" ${s==='locked'?'disabled':`data-course="box" data-box-id="${id}"`} aria-label="الصندوق ${box}: ${label}">${chest(s)}<b>${String(box).padStart(3,'0')}</b><small>${label}</small><span>${PHASES.map((_,j)=>`<i class="${j<count||s==='complete'?'done':j===count&&s==='current'?'active':''}"></i>`).join('')}</span></button>`}).join('')}</div></section>`}
  function mapPage(progress){const m=model(progress);if(!ui.level||ui.level<1||ui.level>5)ui.level=m.currentLevel;return `<main class="course-map">${ui.view==='boxes'?boxesMap(m,ui.level):levelsMap(m)}<p class="course-map-note">${icon(icons.lock,15)} الصندوق التالي يفتح بعد إكمال المراحل الثلاث للصندوق الحالي. الصناديق المكتملة متاحة دائماً للمراجعة.</p></main>`}

  function start(boxId,progress,{review=false}={}){const snap=LiplipProgress.courseSnapshot(progress),record=snap.records.find(x=>x.boxId===boxId);ui.boxId=boxId;ui.review=review;ui.results=false;ui.control=false;ui.storyPage=0;ui.processView=0;ui.notice=review?'وضع المراجعة: لن يتغير تقدمك.':'';ui.error='';ui.phase=review?(record?.completedPhases?.at(-1)||'vocabulary'):(record?.currentPhase||snap.phase||'vocabulary')}
  function recordFor(progress){return LiplipProgress.courseSnapshot(progress).records.find(x=>x.boxId===ui.boxId)||{completedPhases:[],currentPhase:'vocabulary',processIndex:0}}
  function availablePhase(progress,key){const r=recordFor(progress),target=PHASES.findIndex(x=>x.key===key),current=PHASES.findIndex(x=>x.key===r.currentPhase);return ui.review?r.completedPhases.includes(key):target<=current||r.completedPhases.includes(key)}
  function zoneHeader(progress){const loc=location(ui.boxId),r=recordFor(progress);return `<header class="course-zone-head"><button data-course="exit">${icon(icons.back,17)} العودة للخريطة</button><div><span>المستوى ${loc.level} · الصندوق ${loc.box}</span><strong>${phaseDef(ui.phase).label}</strong></div><button data-course="control">${icon(icons.settings,17)} إدارة المحتوى</button></header>${ui.notice?`<p class="course-notice">${safe(ui.notice)}</p>`:''}<nav class="course-phase-toggle" aria-label="مراحل الصندوق">${PHASES.map((p,i)=>{const enabled=availablePhase(progress,p.key),done=r.completedPhases.includes(p.key);return `<button ${enabled?`data-course="phase" data-phase="${p.key}"`:'disabled'} class="${ui.phase===p.key?'active':''} ${done?'done':''}"><b>0${i+1}</b><span>${p.label}<small>${p.short}</small></span>${done?icon(icons.check,16):''}</button>`}).join('')}</nav>`}
  function itemCard(item,i){const media=item.image?`<img src="${safe(item.image)}" alt="${safe(item.ar||item.en)}">`:'';return `<article class="vocab-card ${item.type||'word'}">${media}<span>${String(i+1).padStart(2,'0')} · ${safe(item.type||'word')}</span><strong dir="ltr">${safe(item.en)}</strong><p>${safe(item.ar)}</p>${item.voice?`<button data-course="speak" data-text="${safe(item.voice)}">استمع إلى النطق</button>`:''}</article>`}
  function questions(items,prefix){return items.map((q,i)=>`<fieldset class="course-question"><legend>${i+1}. ${safe(q.prompt)}</legend>${q.image?`<img src="${safe(q.image)}" alt="صورة السؤال">`:''}${q.voice?`<button type="button" data-course="speak" data-text="${safe(q.voice)}">تشغيل الصوت</button>`:''}${Array.isArray(q.options)&&q.options.length?`<div class="course-options" dir="auto">${q.options.map((x,j)=>`<label><input type="radio" name="${prefix}${i}" value="${j}" required>${safe(x)}</label>`).join('')}</div>`:`<input name="${prefix}${i}" required autocomplete="off">`}</fieldset>`).join('')}
  function vocabulary(progress,content,processIndex){if(processIndex===0)return `<section class="phase-vocabulary"><header><span>المرحلة 01 · العملية 01</span><h1>شاهد الكلمة، اسمعها، واستخدمها.</h1><p>الكلمات والجمل والصور والأصوات في مسار واحد قبل الاختبار.</p></header><div class="vocab-deck">${content.items.map(itemCard).join('')}</div><button class="course-advance" data-course="complete-process">أنهيت المحتوى · ابدأ الاختبار</button></section>`;return `<section class="phase-vocabulary"><header><span>المرحلة 01 · العملية 02</span><h1>اختبار المفردات والصوت والصورة.</h1><p>تحتاج ٧٠٪ للانتقال إلى القواعد.</p></header><form id="course-exam-form" data-phase="vocabulary">${questions(content.questions,'q')}<button class="course-submit" type="submit">تحقق من الإجابات</button></form></section>`}
  function grammar(progress,content,processIndex){const a=content.article||{};if(processIndex===0)return `<article class="phase-grammar"><header><span>المرحلة 02 · العملية 01</span><h1>${safe(a.title||'مقال القاعدة')}</h1><p>${safe(a.rule)}</p></header><section class="grammar-formulas"><div><small>Normal</small><strong dir="ltr">${safe(a.normal)}</strong></div><div><small>Negative</small><strong dir="ltr">${safe(a.negative)}</strong></div><div><small>Question</small><strong dir="ltr">${safe(a.question)}</strong></div></section><section class="grammar-notes"><h2>ملاحظات مهمّة</h2><ul>${(a.notes||[]).map(x=>`<li>${safe(x)}</li>`).join('')}</ul></section><section class="grammar-examples"><div><h2>من السهل إلى الصعب</h2><span>${(a.examples||[]).length} مثالاً</span></div>${(a.examples||[]).map((x,i)=>`<p class="${safe(x.difficulty)}"><b>${String(i+1).padStart(2,'0')}</b><span dir="ltr">${safe(x.text)}</span><small>${safe(x.difficulty)}</small></p>`).join('')}</section><button class="course-advance" data-course="complete-process">قرأت المقال · ابدأ اختبار القواعد</button></article>`;return `<section class="phase-grammar"><header><span>المرحلة 02 · العملية 02</span><h1>اختبار القواعد.</h1><p>تحتاج ٧٠٪ للانتقال إلى شاهد واقرأ.</p></header><form id="course-exam-form" data-phase="grammar">${questions(content.questions,'q')}<button class="course-submit" type="submit">تحقق من الإجابات</button></form></section>`}
  function youtubeId(value){const s=String(value||'').trim();if(/^[\w-]{6,20}$/.test(s))return s;try{const u=new URL(s);if(u.hostname==='youtu.be')return u.pathname.slice(1);if(/(^|\.)youtube\.com$/.test(u.hostname))return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||''}catch{}return ''}
  function watchRead(progress,content,processIndex){if(processIndex===0){const video=content.video||{},id=youtubeId(video.youtube);return `<section class="phase-watch"><header><span>المرحلة 03 · العملية 01</span><h1>${safe(video.title||'شاهد الفيديو ثم أجب')}</h1><p>المشاهدة وأسئلتها عملية واحدة.</p></header>${id?`<div class="course-video"><iframe src="https://www.youtube-nocookie.com/embed/${safe(id)}?rel=0" title="${safe(video.title)}" allowfullscreen></iframe></div>`:'<div class="course-empty">أضف رابط YouTube من إدارة المحتوى.</div>'}<form id="course-exam-form" data-phase="watchRead" data-process="video">${questions(content.videoQuestions||[],'q')}<button class="course-submit" type="submit">أنهيت الفيديو والأسئلة</button></form></section>`}const pages=content.story||[],page=pages[Math.min(ui.storyPage,Math.max(0,pages.length-1))];return `<section class="phase-story"><header><span>المرحلة 03 · العملية 02</span><h1>${safe(page?.title||'اقرأ القصة ثم أجب')}</h1><p>القصة وأسئلتها تختمان الصندوق.</p></header>${page?`<article class="story-spread">${page.image?`<img src="${safe(page.image)}" alt="صورة القصة">`:''}<div><span>صفحة ${ui.storyPage+1} من ${pages.length}</span><p dir="ltr">${safe(page.text)}</p><aside>${safe(page.arabic)}</aside></div></article><div class="story-pager"><button data-course="story-prev" ${ui.storyPage===0?'disabled':''}>السابق</button><button data-course="story-next" ${ui.storyPage>=pages.length-1?'disabled':''}>التالي</button></div>`:'<div class="course-empty">أضف صفحات القصة من إدارة المحتوى.</div>'}<form id="course-exam-form" data-phase="watchRead" data-process="story">${questions(content.storyQuestions||[],'q')}<button class="course-submit" type="submit">أنهيت القصة والأسئلة</button></form></section>`}
  function resultScore(record){const vocabulary=record.scores?.['vocabulary:exam']??0,grammar=record.scores?.['grammar:exam']??0,video=record.scores?.['watchRead:video']??0,story=record.scores?.['watchRead:story']??0,watchRead=Math.round((video+story)/2),total=Math.round((vocabulary+grammar+watchRead)/3);return {vocabulary,grammar,watchRead,total}}
  function boxResult(progress){const loc=location(ui.boxId),record=recordFor(progress),score=resultScore(record),next=LiplipProgress.courseSnapshot(progress).currentBox;return `<main class="course-result"><section class="course-result-card"><span class="course-result-kicker">اكتمل الصندوق ${String(loc.box).padStart(3,'0')}</span><div class="course-result-score"><strong>${score.total}%</strong><small>درجة الصندوق</small></div><h1>أحسنت! أكملت المراحل الثلاث.</h1><p>الدرجة تعتمد على إجابات الاختبارات فقط. لكل مرحلة ثلث الدرجة النهائية.</p><div class="course-result-phases"><article><b>33.333%</b><span>المفردات</span><strong>${score.vocabulary}%</strong></article><article><b>33.333%</b><span>القواعد</span><strong>${score.grammar}%</strong></article><article><b>33.333%</b><span>شاهد واقرأ</span><strong>${score.watchRead}%</strong><small>متوسط أسئلة الفيديو والقصة</small></article></div><div class="course-result-actions"><button data-course="result-close">إغلاق</button><button class="primary" data-course="result-next" ${next===null?'disabled':''}>التالي</button><button data-course="result-repeat">تكرار</button></div></section></main>`}
  function learning(progress){if(ui.results)return boxResult(progress);const content=getContent(ui.boxId),r=recordFor(progress),phase=phaseDef(ui.phase),isCompleted=r.completedPhases.includes(ui.phase),processIndex=isCompleted?ui.processView:(ui.phase===r.currentPhase?r.processIndex:0),body=ui.phase==='vocabulary'?vocabulary(progress,content.vocabulary,processIndex):ui.phase==='grammar'?grammar(progress,content.grammar,processIndex):watchRead(progress,content.watchRead,processIndex),reviewNav=isCompleted?`<nav class="course-process-review"><span>مراجعة عمليات ${phase.label}</span>${phase.processes.map((_,i)=>`<button data-course="review-process" data-process="${i}" class="${processIndex===i?'active':''}">العملية ${i+1}</button>`).join('')}</nav>`:'';return `<main class="course-zone ${ui.phase}">${zoneHeader(progress)}${reviewNav}<div class="course-zone-body">${body}</div>${isCompleted?'<p class="course-review-note">هذه مرحلة مكتملة مفتوحة للمراجعة. الإجابات هنا لا تغيّر التقدّم.</p>':''}${ui.control?controlPanel():''}</main>`}

  const HEADERS={
    vocabulary:['Phase','Level','Box','Feature','Order','English','Arabic','Image URL','Voice text','Question','Option 1','Option 2','Option 3','Option 4','Correct option','Answer','Explanation'],
    grammar:['Phase','Level','Box','Feature','Order','Title','Grammar law','Normal formula','Negative formula','Question formula','Important notes','Example','Difficulty','Question','Option 1','Option 2','Option 3','Option 4','Correct option','Answer','Explanation'],
    watchRead:['Phase','Level','Box','Feature','Order','Title','Video URL','Story text','Arabic text','Image URL','Question','Option 1','Option 2','Option 3','Option 4','Correct option','Answer','Explanation']
  };
  const FEATURE_HELP={vocabulary:'word · sentence · image · voice · vocabularyExam · voiceExam · imageExam',grammar:'grammarArticle · grammarExample · grammarExam',watchRead:'video · videoExam · story · storyExam'};
  function controlPanel(){const loc=location(ui.boxId);return `<div class="course-control-overlay"><button class="course-control-backdrop" data-course="control-close" aria-label="إغلاق"></button><section class="course-control" role="dialog" aria-modal="true"><header><div><small>المستوى ${loc.level} · الصندوق ${loc.box}</small><h2>إدارة محتوى المراحل</h2></div><button data-course="control-close">إغلاق</button></header><p>لكل مرحلة ملف Excel مستقل. عمود Phase يقبل قيمة واحدة فقط، ولا يوجد عمود Step.</p><div class="course-template-grid">${PHASES.map(p=>`<article class="${p.key}"><span>${p.label}</span><h3>${PHASE_FILE[p.key]}</h3><code>Phase = ${PHASE_VALUE[p.key]}</code><small>${FEATURE_HELP[p.key]}</small><div><button data-course="download-template" data-phase="${p.key}">تنزيل القالب</button><label>استيراد الملف<input type="file" data-course-import="${p.key}" accept=".xlsx"></label></div></article>`).join('')}</div>${ui.error?`<p class="course-control-error">${safe(ui.error)}</p>`:ui.notice?`<p class="course-control-success">${safe(ui.notice)}</p>`:''}</section></div>`}

  function xmlEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
  function colName(i){let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s}
  function worksheet(rows){return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>`<c r="${colName(ci)}${ri+1}" t="inlineStr"${ri===0?' s="1"':''}><is><t>${xmlEsc(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${colName(rows[0].length-1)}${rows.length}"/></worksheet>`}
  function templateRows(phase){
    const h=HEADERS[phase],p=PHASE_VALUE[phase];
    if(phase==='vocabulary')return [h,[p,1,1,'word',1,'hello','مرحباً','','hello','','','','','','','',''],[p,1,1,'imageExam',2,'','','https://example.com/cat.jpg','','ما هذه الصورة؟','cat','dog','book','car',1,'cat','اختر الصورة أو الكلمة الصحيحة.']];
    if(phase==='grammar')return [h,[p,1,1,'grammarArticle',1,'Present simple','نستخدمه للعادات والحقائق.','Subject + verb + object','Subject + do/does not + verb','Do/Does + subject + verb?','does مع he/she/it','','','','','','','','','',''],...Array.from({length:10},(_,i)=>[p,1,1,'grammarExample',i+2,'','','','','','',`Example ${i+1}: She reads every day.`,i<4?'easy':i<8?'medium':'difficult','','','','','','','','']),[p,1,1,'grammarExam',12,'','','','','','','','','اختر الصيغة الصحيحة.','She reads','She read','Reads she','She reading',1,'She reads','']];
    return [h,[p,1,1,'video',1,'Introduction','https://www.youtube.com/watch?v=VIDEO_ID','','','','','','','','','','',''],[p,1,1,'videoExam',2,'','','','','','ما الفكرة الأساسية؟','A','B','C','D',1,'A',''],[p,1,1,'story',3,'Story','','A short story.','قصة قصيرة.','https://example.com/story.jpg','','','','','','','',''],[p,1,1,'storyExam',4,'','','','','','ماذا حدث؟','A','B','C','D',1,'A','']];
  }
  async function downloadTemplate(phase){if(typeof JSZip==='undefined')throw Error('JSZip غير متاح.');const zip=new JSZip(),rows=templateRows(phase);zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');const xl=zip.folder('xl');xl.file('workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Content" sheetId="1" r:id="rId1"/></sheets></workbook>');xl.folder('_rels').file('workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');xl.file('styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font/><font><b/><color rgb="FFFFFFFF"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF65538E"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf/><xf fontId="1" fillId="2" applyFont="1" applyFill="1"/></cellXfs></styleSheet>');xl.folder('worksheets').file('sheet1.xml',worksheet(rows));const blob=await zip.generateAsync({type:'blob'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=PHASE_FILE[phase];document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
  function cellText(cell,shared){const type=cell.getAttribute('t'),v=cell.getElementsByTagName('v')[0]?.textContent||'';if(type==='s')return shared[Number(v)]||'';if(type==='inlineStr')return [...cell.getElementsByTagName('t')].map(x=>x.textContent||'').join('');return v}
  async function xlsxRows(file){if(typeof JSZip==='undefined')throw Error('قارئ Excel غير متاح.');const zip=await JSZip.loadAsync(await file.arrayBuffer()),sharedFile=zip.file('xl/sharedStrings.xml'),shared=[];if(sharedFile){const doc=new DOMParser().parseFromString(await sharedFile.async('text'),'application/xml');for(const si of doc.getElementsByTagName('si'))shared.push([...si.getElementsByTagName('t')].map(x=>x.textContent||'').join(''))}const sheet=zip.file('xl/worksheets/sheet1.xml');if(!sheet)throw Error('ورقة Content غير موجودة.');const doc=new DOMParser().parseFromString(await sheet.async('text'),'application/xml'),out=[];for(const row of doc.getElementsByTagName('row')){const values=[];for(const c of row.getElementsByTagName('c')){const ref=c.getAttribute('r')||'',letters=(ref.match(/[A-Z]+/)||['A'])[0];let index=0;for(const ch of letters)index=index*26+ch.charCodeAt(0)-64;values[index-1]=cellText(c,shared)}out.push(values)}return out}
  const n=(v,min,max)=>{const x=Number(v);return Number.isInteger(x)&&x>=min&&x<=max?x:null};
  const opts=(row,start)=>row.slice(start,start+4).map(x=>String(x||'').trim()).filter(Boolean);
  function question(row,{prompt,optionStart,correct,answer,explanation,voice='',image=''}){const options=opts(row,optionStart),c=n(row[correct],1,4);return {type:options.length?'mcq':'write',prompt:String(row[prompt]||'').trim(),options,correct:c===null?0:c-1,answer:String(row[answer]||'').trim(),explanation:String(row[explanation]||'').trim(),voice:String(row[voice]||'').trim(),image:String(row[image]||'').trim()}}
  function importRows(phase,rows){const expected=HEADERS[phase];if(!rows.length||expected.some((h,i)=>String(rows[0]?.[i]||'').trim()!==h))throw Error('عناوين الأعمدة لا تطابق قالب '+phaseDef(phase).label+'.');let count=0;const touched=new Set();for(let ri=1;ri<rows.length;ri++){const row=rows[ri]||[];if(!row.some(x=>String(x||'').trim()))continue;if(String(row[0]||'').trim().toLowerCase()!==PHASE_VALUE[phase])throw Error(`الصف ${ri+1}: Phase يجب أن يكون ${PHASE_VALUE[phase]} فقط.`);const level=n(row[1],1,5),box=n(row[2],1,LEVEL_BOXES);if(!level||!box)throw Error(`الصف ${ri+1}: Level أو Box غير صالح.`);const id=globalId(level,box),content=getContent(id),feature=String(row[3]||'').trim(),order=n(row[4],1,999)||ri;if(!touched.has(id)){if(phase==='vocabulary')content.vocabulary={items:[],questions:[]};if(phase==='grammar')content.grammar={article:{title:'',rule:'',normal:'',negative:'',question:'',notes:[],examples:[]},questions:[]};if(phase==='watchRead')content.watchRead={video:{title:'',youtube:''},videoQuestions:[],story:[],storyQuestions:[]};touched.add(id)}
      if(phase==='vocabulary'){if(['word','sentence','image','voice'].includes(feature))content.vocabulary.items.push({type:feature,order,en:String(row[5]||'').trim(),ar:String(row[6]||'').trim(),image:String(row[7]||'').trim(),voice:String(row[8]||'').trim()});else if(['vocabularyExam','voiceExam','imageExam'].includes(feature))content.vocabulary.questions.push(question(row,{prompt:9,optionStart:10,correct:14,answer:15,explanation:16,voice:8,image:7}));else throw Error(`الصف ${ri+1}: Feature غير صالح.`)}
      if(phase==='grammar'){if(feature==='grammarArticle'){content.grammar.article={title:String(row[5]||'').trim(),rule:String(row[6]||'').trim(),normal:String(row[7]||'').trim(),negative:String(row[8]||'').trim(),question:String(row[9]||'').trim(),notes:String(row[10]||'').split(/\r?\n/).filter(Boolean),examples:content.grammar.article?.examples||[]}}else if(feature==='grammarExample')content.grammar.article.examples.push({text:String(row[11]||'').trim(),difficulty:String(row[12]||'easy').trim()});else if(feature==='grammarExam')content.grammar.questions.push(question(row,{prompt:13,optionStart:14,correct:18,answer:19,explanation:20}));else throw Error(`الصف ${ri+1}: Feature غير صالح.`)}
      if(phase==='watchRead'){if(feature==='video')content.watchRead.video={title:String(row[5]||'').trim(),youtube:String(row[6]||'').trim()};else if(feature==='videoExam')content.watchRead.videoQuestions.push(question(row,{prompt:10,optionStart:11,correct:15,answer:16,explanation:17}));else if(feature==='story')content.watchRead.story.push({order,title:String(row[5]||'').trim(),text:String(row[7]||'').trim(),arabic:String(row[8]||'').trim(),image:String(row[9]||'').trim()});else if(feature==='storyExam')content.watchRead.storyQuestions.push(question(row,{prompt:10,optionStart:11,correct:15,answer:16,explanation:17}));else throw Error(`الصف ${ri+1}: Feature غير صالح.`)}
      storeBox(id,content);count++}return count}
  async function importFile(phase,file){ui.error='';ui.notice='';try{const rows=await xlsxRows(file),count=importRows(phase,rows);ui.notice=`تم استيراد ${count} صفاً لمرحلة ${phaseDef(phase).label}.`;return true}catch(e){ui.error=e.message||'تعذّر استيراد الملف.';return false}}

  function grade(items,form){if(!items.length)return 100;let correct=0;items.forEach((q,i)=>{const answer=String(form.get('q'+i)||'').trim();if(q.options?.length){if(Number(answer)===q.correct)correct++}else if(norm(answer)===norm(q.answer))correct++});return Math.round(correct/items.length*100)}
  function currentQuestions(content,phase,process){if(phase==='vocabulary')return content.vocabulary.questions;if(phase==='grammar')return content.grammar.questions;return process==='video'?content.watchRead.videoQuestions:content.watchRead.storyQuestions}
  function speak(text){if(!text||!window.speechSynthesis||typeof SpeechSynthesisUtterance==='undefined')return;try{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;window.speechSynthesis.speak(u)}catch{}}
  function click(action,target,progress){
    if(action==='level'){const level=Number(target.dataset.level),m=model(progress);if(m.statusLevel(level)==='locked')return {};ui.level=level;ui.view='boxes';return {}}
    if(action==='levels'){ui.view='levels';return {}}
    if(action==='box'){const id=Number(target.dataset.boxId),m=model(progress),status=m.statusBox(id);if(status==='locked')return {};start(id,progress,{review:status==='complete'});return {open:true}}
    if(action==='exit'||action==='result-close'){ui.control=false;ui.results=false;ui.view='boxes';return {exit:true}}
    if(action==='result-next'){const next=LiplipProgress.courseSnapshot(progress).currentBox;if(next===null)return {};start(next,progress);return {open:true}}
    if(action==='result-repeat'){const boxId=ui.boxId;start(boxId,progress,{review:true});ui.phase='vocabulary';ui.processView=0;return {open:true}}
    if(action==='control'){ui.control=true;ui.error='';return {}}
    if(action==='control-close'){ui.control=false;return {}}
    if(action==='phase'){const key=target.dataset.phase;if(availablePhase(progress,key)){ui.phase=key;ui.storyPage=0;ui.processView=0}return {}}
    if(action==='review-process'){const value=Number(target.dataset.process);if(recordFor(progress).completedPhases.includes(ui.phase)&&[0,1].includes(value)){ui.processView=value;ui.storyPage=0}return {}}
    if(action==='speak'){speak(target.dataset.text);return {}}
    if(action==='story-prev'){ui.storyPage=Math.max(0,ui.storyPage-1);return {}}
    if(action==='story-next'){ui.storyPage++;return {}}
    if(action==='download-template'){downloadTemplate(target.dataset.phase).catch(e=>{ui.error=e.message});return {noRender:true}}
    if(action==='complete-process'){const r=recordFor(progress);if(ui.review||r.completedPhases.includes(ui.phase))return {};try{return {progress:LiplipProgress.recordCourseProcess(progress,{boxId:ui.boxId,phase:ui.phase,process:phaseDef(ui.phase).processes[r.processIndex],score:100}),completed:true}}catch(e){ui.error=e.message;return {}}}
    return {}
  }
  function submit(form,progress){if(form.id!=='course-exam-form')return {};const phase=form.dataset.phase,process=form.dataset.process||'exam',content=getContent(ui.boxId),items=currentQuestions(content,phase,process),score=grade(items,new FormData(form));ui.notice=`النتيجة: ${score}%`;if(score<70){ui.notice+=` · تحتاج ٧٠٪. راجع المحتوى وحاول مرة أخرى.`;return {}}const r=recordFor(progress);if(ui.review||r.completedPhases.includes(phase)){ui.notice+=` · مراجعة فقط.`;return {}}try{return {progress:LiplipProgress.recordCourseProcess(progress,{boxId:ui.boxId,phase,process:phaseDef(phase).processes[r.processIndex],score,words:content.vocabulary.items.filter(x=>x.type==='word').map(x=>({word:x.en,ar:x.ar,image:x.image||'',example:content.vocabulary.items.find(y=>y.type==='sentence')?.en||''})),grammar:[content.grammar.article]}),completed:true}}catch(e){ui.error=e.message;return {}}}
  function afterProgress(progress){const r=recordFor(progress);ui.processView=0;if(r.completedPhases.length===3){ui.results=true;ui.review=false;ui.phase='watchRead';ui.notice=''}else{ui.phase=r.currentPhase;ui.notice=`اكتملت العملية. التالي: ${phaseDef(r.currentPhase).label} · ${r.processIndex===0?'العملية الأولى':'العملية الثانية'}.`}}
  function render(progress){return learning(progress)}
  return {PHASES,HEADERS,LEVEL_BOXES,mapPage,start,render,click,submit,afterProgress,importFile,downloadTemplate,getContent,model};
})();
