/* Study zone: browser-local content and resumable learner state. */
const LiplipZone = (() => {
 const CONTENT_KEY='liplip-zone-content-v1', STATE_KEY='liplip-zone-state-v1';
 const PHASES=[
  {key:'vocab',name:'مفردات',detail:'بطاقة وراء بطاقة'},
  {key:'checkpointVocab',name:'فحص الفهم',detail:'بعد المفردات'},
  {key:'listen',name:'استمع وتكلّم',detail:'صوت وراء صوت'},
  {key:'checkpointListen',name:'فحص السمع',detail:'بعد الاستماع'},
  {key:'grammar',name:'القواعد',detail:'قاعدة وتطبيق معاً'},
  {key:'exam',name:'امتحان الصندوق',detail:'المرحلة الأخيرة'}
 ];
 const PROCESS_LABEL={vocab:'المفردات',checkpointVocab:'فحص المفردات',listen:'الاستماع والنطق',checkpointListen:'فحص الاستماع',grammar:'القواعد',exam:'الامتحان النهائي'};
 const TYPES={
  vocab:[['word','كلمة'],['sentence','جملة'],['imageWord','كلمة مع صورة']],
  listen:[['word','صوت كلمة'],['sentence','صوت جملة'],['imageWord','استمع وانطق مع صورة']],
  checkpointVocab:[['choice','سؤال اختيارات'],['imageChoice','اختر ما في الصورة'],['imageWrite','اكتب ما في الصورة'],['imageSpeak','انطق ما في الصورة']],
  checkpointListen:[['audioChoice','سؤال صوت واختيارات']],
  grammar:[['sentenceRule','قانون إنشاء جملة'],['questionRule','قانون إنشاء سؤال'],['note','ملاحظة'],['addition','إضافة'],['example','مثال'],['choice','سؤال اختبار']],
  exam:[['choice','سؤال اختيارات'],['write','اكتب الإجابة'],['imageChoice','اختر ما في الصورة'],['imageWrite','اكتب ما في الصورة'],['imageSpeak','انطق ما في الصورة']]
 };
 const MAX_ITEMS={vocab:60,listen:60,checkpointVocab:30,checkpointListen:30,grammar:30,exam:30};
 const GRAMMAR={
  1:{sentence:'الفاعل + الفعل + التكملة',question:'أداة السؤال + الفعل المساعد + الفاعل؟',example:'I am from Iraq.',questionExample:'How are you?',quiz:'اختر السؤال الصحيح',quizOptions:['How are you?','How you are?','You are how?'],quizCorrect:0},
  2:{sentence:'I am + الاسم أو الصفة',question:'What + is + your + name?',example:'My name is Ali.',questionExample:'What is your name?',quiz:'اختر جملة تعريف صحيحة',quizOptions:['My name is Ali.','My name Ali.','I name is Ali.'],quizCorrect:0},
  3:{sentence:'The + المكان + is + الوصف',question:'Where + is + the + المكان?',example:'The market is open.',questionExample:'Where is the market?',quiz:'اختر السؤال عن مكان السوق',quizOptions:['Where is the market?','Where the market is?','Is where market?'],quizCorrect:0},
  4:{sentence:'I + الفعل بصيغته الأساسية + التكملة',question:'Do + you + الفعل + التكملة؟',example:'I study in the morning.',questionExample:'Do you study in the morning?',quiz:'اختر سؤال المضارع البسيط',quizOptions:['Do you study?','You do study?','Does you study?'],quizCorrect:0},
  5:{sentence:'I would like + الشيء',question:'Would + you + like + الشيء؟',example:'I would like some tea.',questionExample:'Would you like tea?',quiz:'اختر طريقة مهذبة للطلب',quizOptions:['I would like tea.','I like would tea.','Would I tea like.'],quizCorrect:0}
 };
 const GRAMMAR_TOPICS={1:'التحية والسؤال عن الحال',2:'التعريف بالنفس والاسم',3:'وصف الأماكن والسؤال عنها',4:'المضارع البسيط: الحديث عن العادات',5:'الطلب المهذب باستخدام would like'};
 const SENTENCES={
  1:['How are you?','كيف حالك؟'],2:['My name is Ali.','اسمي علي.'],3:['The market is open.','السوق مفتوح.'],4:['I study in the morning.','أدرس في الصباح.'],5:['I would like some tea.','أود بعض الشاي.']
 };
 const blank=()=>Object.fromEntries(Object.keys(TYPES).map(k=>[k,[]]));
 const clone=value=>JSON.parse(JSON.stringify(value));
 let contentEdits={};
 try{const raw=JSON.parse(localStorage.getItem(CONTENT_KEY)||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))for(const [key,value] of Object.entries(raw)){const id=Number(key);if(Number.isInteger(id)&&id>=1&&id<=1000)try{contentEdits[id]=validateContent(value)}catch{}}}catch{}
 function seed(id){const data=blank();const base=LiplipContent.get(id);if(id>5||!base.words.length)return data;
  data.vocab=base.words.map((w,i)=>({id:`v${i}`,type:'word',en:w.term,ar:w.meaning,example:w.example}));
  const pair=SENTENCES[id];data.vocab.push({id:'vs',type:'sentence',en:pair[0],ar:pair[1],example:base.words[0].example});
  data.listen=base.words.slice(0,3).map((w,i)=>({id:`l${i}`,type:'word',en:w.term,ar:w.meaning}));
  data.listen.push({id:'ls',type:'sentence',en:pair[0],ar:pair[1]});
  const meanings=base.words.slice(0,3).map(w=>w.meaning);
  data.checkpointVocab=[{id:'cv1',type:'choice',prompt:`ما معنى ${base.words[0].term}؟`,options:meanings,correct:0,explanation:`${base.words[0].term} تعني ${meanings[0]}.`},{id:'cv2',type:'choice',prompt:`اختر معنى ${base.words[1].term}`,options:[meanings[2],meanings[1],meanings[0]],correct:1,explanation:`${base.words[1].term} تعني ${meanings[1]}.`}];
  data.checkpointListen=[{id:'cl1',type:'audioChoice',prompt:'استمع واختر المعنى الصحيح',audio:base.words[0].term,options:meanings,correct:0,explanation:`سمعت ${base.words[0].term}.`},{id:'cl2',type:'audioChoice',prompt:'استمع إلى الكلمة التالية',audio:base.words[1].term,options:[meanings[2],meanings[1],meanings[0]],correct:1,explanation:`سمعت ${base.words[1].term}.`}];
  const g=GRAMMAR[id];data.grammar=[{id:'gs',type:'sentenceRule',title:GRAMMAR_TOPICS[id],formula:g.sentence,body:'رتّب الأجزاء بهذا الترتيب ثم غيّر الكلمات لتحكي عن نفسك.',example:g.example},{id:'gq',type:'questionRule',title:'كيف تنشئ سؤالاً؟',formula:g.question,body:'قدّم أداة السؤال ثم اتبع ترتيب الكلمات في النموذج.',example:g.questionExample},{id:'gn',type:'note',title:'لاحظ الترتيب',body:'ترتيب الكلمات في الإنجليزية مهم؛ تغيير موقع الكلمة قد يغيّر المعنى.'},{id:'ga',type:'addition',title:'جرّب بنفسك',body:'بدّل الاسم أو المكان أو الوقت في المثال، ثم اقرأ الجملة الجديدة بصوت مرتفع.'},{id:'ge',type:'example',en:g.example,ar:id===1?'أنا من العراق.':pair[1],body:'اقرأ الجملة ثم قارنها بالقانون أعلاه.'},{id:'gt',type:'choice',prompt:g.quiz,options:g.quizOptions,correct:g.quizCorrect,explanation:'ارجع إلى القانون ثم لاحظ ترتيب الكلمات.'}];
  data.exam=[{id:'e1',type:'choice',prompt:`ما معنى ${base.words[2].term}؟`,options:[meanings[0],base.words[2].meaning,meanings[1]],correct:1,explanation:'ارجع إلى بطاقات المفردات.'},{id:'e2',type:'choice',prompt:g.quiz,options:g.quizOptions,correct:g.quizCorrect,explanation:'راجع قانون الجملة أو السؤال.'},{id:'e3',type:'write',prompt:`اكتب بالإنجليزية: ${base.words[0].meaning}`,answer:base.words[0].term,explanation:'اكتب الكلمة كما ظهرت في البطاقة.'}];
  return data;
 }
 function validateItem(process,item){if(!TYPES[process]?.some(([type])=>type===item?.type))throw Error('نوع المحتوى غير صحيح.');const v={id:typeof item.id==='string'&&/^[a-zA-Z0-9_-]{1,40}$/.test(item.id)?item.id:`i${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`,type:item.type};
  const field=(key,max=300)=>{const value=String(item[key]||'').trim();if(!value||value.length>max)throw Error('أكمل الحقول المطلوبة ضمن حدودها.');v[key]=value};
  if(process==='vocab'){field('en',120);field('ar',160);field('example',220)}
  else if(process==='listen'){field('en',120);field('ar',160)}
  else if(['choice','audioChoice','imageChoice'].includes(item.type)){field('prompt',220);if(item.type==='audioChoice')field('audio',120);if(!Array.isArray(item.options)||item.options.length!==3)throw Error('أضف ثلاثة خيارات.');v.options=item.options.map(x=>{const a=String(x||'').trim();if(!a||a.length>120)throw Error('أكمل الخيارات الثلاثة.');return a});v.correct=Number(item.correct);if(![0,1,2].includes(v.correct))throw Error('اختر الإجابة الصحيحة.');field('explanation',250)}
  else if(['write','imageWrite','imageSpeak'].includes(item.type)){field('prompt',220);field('answer',120);field('explanation',250)}
  else if(item.type==='sentenceRule'||item.type==='questionRule'){field('title',120);field('formula',220);field('body',500);field('example',220)}
  else if(item.type==='note'||item.type==='addition'){field('title',120);field('body',500)}
  else if(item.type==='example'){field('en',220);field('ar',220);field('body',500)}
  if(item.type.startsWith('image')){field('image',500);try{const url=new URL(v.image,typeof location==='undefined'?'https://liplip.pages.dev/':location.href);if(url.protocol!=='https:'||url.username||url.password||!/^https:\/\//i.test(v.image))throw Error();}catch{throw Error('رابط الصورة يجب أن يبدأ بـ https:// وأن يكون رابطاً مباشراً صالحاً.')}}
  return v;
 }
 function validateContent(value){const result=blank();for(const process of Object.keys(TYPES)){const list=value?.[process];if(!Array.isArray(list)||list.length>MAX_ITEMS[process])throw Error('عدد العناصر غير صحيح.');result[process]=list.map(item=>validateItem(process,item));const ids=new Set(result[process].map(item=>item.id));if(ids.size!==result[process].length)throw Error('معرفات العناصر مكررة.')}return result}
 function getContent(id){return clone(contentEdits[id]||seed(id))}
 function saveContent(id,value){if(!Number.isInteger(id)||id<1||id>1000)throw Error('صندوق غير صحيح.');contentEdits[id]=validateContent(value);try{localStorage.setItem(CONTENT_KEY,JSON.stringify(contentEdits));return true}catch{return false}}
 function norm(text){return String(text||'').toLocaleLowerCase().trim().replace(/[.,!?;:]+$/g,'').replace(/\s+/g,' ')}
 let progress={boxId:null,phase:0,card:0,flipped:false,reviewed:[],spoken:{},imageSpoken:{},answers:{},attempts:{},feedback:'',revision:0};
 let ui={sheet:false,screen:'menu',process:'vocab',type:'word',targetBox:null,selectedId:null,draft:null,notice:'',deleteConfirm:false,micBusy:false,recording:false,playingQuestion:null};
 let importing={scope:null,stage:null,step:null,box:null,review:null,error:'',busy:false};
 let importToken=0;
 let capture=null,captureToken=0;
 const recordings=new Map();
 let playbackToken=0,lastAutoWord='';
 function persist(){try{localStorage.setItem(STATE_KEY,JSON.stringify(progress));return true}catch{return false}}
 function cancelCapture(){captureToken++;if(capture){const {recorder,release}=capture;capture=null;try{if(recorder.state==='recording')recorder.stop()}catch{}release()}ui.micBusy=false;ui.recording=false}
 function start(boxId){if(!Number.isInteger(boxId)||boxId<1||boxId>1000)return;lastAutoWord='';cancelCapture();recordings.clear();importToken++;importing={scope:null,stage:null,step:null,box:null,review:null,error:'',busy:false};progress={boxId,phase:0,card:0,flipped:false,reviewed:[],spoken:{},imageSpoken:{},answers:{},attempts:{},feedback:'',revision:0};try{const saved=JSON.parse(localStorage.getItem(STATE_KEY)||'null');if(saved?.boxId===boxId&&Number.isInteger(saved.phase)&&saved.phase>=0&&saved.phase<PHASES.length){progress={...progress,...saved,boxId};progress.reviewed=Array.isArray(saved.reviewed)?saved.reviewed.filter(Number.isInteger):[];progress.spoken=saved.spoken&&typeof saved.spoken==='object'?saved.spoken:{};progress.imageSpoken=saved.imageSpoken&&typeof saved.imageSpoken==='object'?saved.imageSpoken:{};progress.answers=saved.answers&&typeof saved.answers==='object'?saved.answers:{};progress.attempts=saved.attempts&&typeof saved.attempts==='object'?saved.attempts:{}}}catch{}ui={sheet:false,screen:'menu',process:'vocab',type:'word',targetBox:boxId,selectedId:null,draft:null,notice:'',deleteConfirm:false,micBusy:false,recording:false,playingQuestion:null,previewBox:null}}
 function resetAfterEdit(id){if(id===progress.boxId){lastAutoWord='';cancelCapture();recordings.clear();progress={boxId:id,phase:0,card:0,flipped:false,reviewed:[],spoken:{},imageSpoken:{},answers:{},attempts:{},feedback:'تغيّر محتوى الصندوق؛ بدأت مراحله من جديد.',revision:progress.revision+1};persist()}}
 function clear(){try{localStorage.removeItem(STATE_KEY)}catch{}lastAutoWord='';cancelCapture();recordings.clear();importToken++;importing.review=null;progress.boxId=null;ui.previewBox=null;ui.playingQuestion=null;playbackToken++;window.speechSynthesis?.cancel?.()}
 function speak(text,onfinish){if(!('speechSynthesis' in window)||typeof SpeechSynthesisUtterance==='undefined'){progress.feedback='الصوت غير متاح؛ اقرأ النص بصوت مرتفع.';return false}try{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.85;if(onfinish){u.onend=onfinish;u.onerror=onfinish}window.speechSynthesis.speak(u);return true}catch{progress.feedback='تعذّر تشغيل الصوت في هذا المتصفح.';return false}}
 async function mic(index,update){
  if(capture?.index===index&&capture.recorder.state==='recording'){
   ui.recording=false;ui.micBusy=true;
   try{capture.recorder.stop()}catch{cancelCapture();progress.feedback='تعذّر إنهاء التسجيل؛ جرّب مجدداً.';update()}
   update();return
  }
  if(ui.micBusy||ui.recording)return;
  if(typeof navigator==='undefined'||!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){progress.feedback='هذا المتصفح لا يدعم تسجيل الصوت. جرّب متصفحاً يدعم الميكروفون.';update();return}
  const token=++captureToken,boxId=progress.boxId;
  ui.micBusy=true;progress.feedback='بانتظار إذن الميكروفون…';update();
  let stream;
  try{
   stream=await navigator.mediaDevices.getUserMedia({audio:true});
   if(token!==captureToken||progress.boxId!==boxId||(String(index).startsWith('image:')?!getContent(boxId)[PHASES[progress.phase].key]?.some(item=>'image:'+item.id===index):PHASES[progress.phase].key!=='listen'||progress.card!==index)){stream.getTracks().forEach(track=>track.stop());return}
   const recorder=new MediaRecorder(stream),chunks=[];let released=false;
   const release=()=>{if(!released){released=true;stream.getTracks().forEach(track=>track.stop())}};
   capture={index,recorder,release};
   recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};
   recorder.onerror=()=>{if(token!==captureToken)return;cancelCapture();progress.feedback='حدث خطأ أثناء التسجيل. حاول مجدداً.';update()};
   recorder.onstop=()=>{
    release();
    if(token!==captureToken||progress.boxId!==boxId)return;
    capture=null;ui.micBusy=false;ui.recording=false;
    const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});
    if(blob.size){recordings.set(index,blob);if(String(index).startsWith('image:'))progress.imageSpoken[index.slice(6)]=true;else progress.spoken[index]={method:'recorded',matched:false};progress.feedback='اكتمل التسجيل. يمكنك الانتقال أو الضغط على الميكروفون لتسجيل محاولة جديدة.';persist()}
    else progress.feedback='لم يصل صوت في التسجيل. اضغط الميكروفون وحاول مرة أخرى.';
    update()
   };
   recorder.start();
   if(String(index).startsWith('image:'))delete progress.imageSpoken[index.slice(6)];else delete progress.spoken[index];recordings.delete(index);persist();
   ui.micBusy=false;ui.recording=true;progress.feedback='الميكروفون يعمل؛ قل العبارة ثم اضغط البطاقة لإيقاف التسجيل.';update()
  }catch(error){stream?.getTracks().forEach(track=>track.stop());if(token!==captureToken)return;capture=null;ui.micBusy=false;ui.recording=false;progress.feedback=error?.name==='NotAllowedError'?'لم يُسمح باستخدام الميكروفون. فعّل الإذن ثم جرّب مرة أخرى.':'تعذّر فتح الميكروفون أو التسجيل؛ حاول مجدداً.';update()}
 }
 function canAdvance(content){const phase=PHASES[progress.phase].key;if(phase==='vocab')return content.vocab.length>0&&progress.reviewed.length>=content.vocab.length;if(phase==='listen')return content.listen.length>0&&content.listen.every((_,i)=>progress.spoken[i]?.method==='recorded');return false}
 function completedData(){const content=getContent(progress.boxId);const pronunciation=0; // A recording does not establish pronunciation accuracy.
  const examWrite=content.exam.filter(x=>x.type==='write');const writing=examWrite.length?Math.round(examWrite.reduce((sum,x)=>sum+100/(progress.attempts[x.id]||1),0)/examWrite.length):0;return {words:content.vocab.filter(x=>x.type==='word').map(x=>x.en),pronunciation,writing}}
 async function importFile(file,update){
  if(!ui.sheet||ui.screen!=='menu')return;
  const token=++importToken;importing.error='';importing.busy=true;ui.notice='';update();
  try{
   const result=await LiplipImporter.read(file,validateItem);
   if(token!==importToken)return;
   const next={...contentEdits};
   let added=0,already=0;
   const changed=[];
   for(const [id,box] of result.boxes){
    const current=getContent(id);
    let boxChanged=false;
    for(const process of Object.keys(TYPES)){
     const list=current[process];
     const signature=item=>JSON.stringify(Object.entries(item).filter(([key])=>key!=='id'));
     const signatures=new Set(list.map(signature));
     const ids=new Set(list.map(item=>item.id));
     for(const item of box[process]){
      const key=signature(item);
      if(signatures.has(key)){already++;continue}
      if(list.length>=MAX_ITEMS[process])throw Error(`الصندوق ${id}: وصل الجزء «${PROCESS_LABEL[process]}» إلى ${MAX_ITEMS[process]} عنصراً. لم يُضف شيء.`);
      while(ids.has(item.id))item.id=`i${Math.random().toString(36).slice(2,12)}`;
      list.push(item);ids.add(item.id);signatures.add(key);added++;boxChanged=true;
     }
    }
    if(boxChanged){next[id]=current;changed.push(id)}
   }
   if(added){
    try{localStorage.setItem(CONTENT_KEY,JSON.stringify(next))}
    catch{throw Error('لم تتسع مساحة التخزين المحلية للمحتوى. لم يُضف أي عنصر.')}
    contentEdits=next;
    if(changed.includes(progress.boxId))resetAfterEdit(progress.boxId);
   }
   importing.firstBox=Math.min(...result.boxes.keys());
   const location=LiplipProgress.location(importing.firstBox);
   ui.notice=`أُضيف ${added} عنصر جديد في ${changed.length} صندوق. ${already?`${already} عنصر موجود مسبقاً لم يُكرّر. `:''}أول موقع في الملف: المستوى ${location.stage}، الخطوة ${location.step}، الصندوق ${location.box}.`;
   ui.screen='import-result';
  }catch(error){if(token===importToken)importing.error=error.message||'تعذّرت قراءة الملف.'}
  finally{if(token===importToken){importing.busy=false;update()}}
 }
 function click(action,el,update){const content=getContent(progress.boxId);const phase=PHASES[progress.phase].key;progress.feedback='';if(action==='exit'){importToken++;importing.review=null;persist();ui.playingQuestion=null;playbackToken++;window.speechSynthesis?.cancel?.();cancelCapture();recordings.clear();return {exit:true}}
  if(action==='control'){if(ui.sheet){importToken++;importing.review=null}ui.sheet=!ui.sheet;ui.screen='menu';update();return {}}
  if(action==='close-sheet'){ui.sheet=false;importToken++;importing.review=null;update();return {}}
  if(action==='flip'){progress.flipped=!progress.flipped;persist();update();return {}}
  if(action==='mark-sentence'){if(!progress.reviewed.includes(progress.card))progress.reviewed.push(progress.card);persist();update();return {}}
  if(action==='replay-word'){const item=content.vocab[progress.card];if(item&&item.type!=='sentence')speak(item.en);return {}}
  if(action==='image-mic'){mic('image:'+el.dataset.id,update);return {}}
  if(action==='image-audio'){const item=content[phase].find(q=>q.id===el.dataset.id);if(item?.answer)speak(item.answer);return {}}
  if(action==='audio'){const index=Number(el.dataset.index);const process=el.dataset.process||phase;const item=content[process]?.[index];if(item)speak(item.en||item.audio||item.example);update();return {}}
  if(action==='audio-question'){const index=Number(el.dataset.index),process=el.dataset.process;const questions=content[process]?.filter(x=>['choice','audioChoice','write'].includes(x.type));const item=questions?.[index];if(phase!==process||item?.type!=='audioChoice')return {};const key=process+':'+item.id;if(ui.playingQuestion===key){ui.playingQuestion=null;playbackToken++;window.speechSynthesis?.cancel?.();update();return {}}ui.playingQuestion=key;const boxId=progress.boxId,token=++playbackToken;const started=speak(item.audio,()=>{if(token===playbackToken&&ui.playingQuestion===key&&progress.boxId===boxId){ui.playingQuestion=null;update()}});if(!started)ui.playingQuestion=null;update();return {}}
  if(action==='mic'){mic(Number(el.dataset.index),update);return {}}
  if(action==='prev'){progress.card=Math.max(0,progress.card-1);progress.flipped=false;persist();update();return {}}
  if(action==='next'){
   if(phase==='vocab'){
    if(!progress.flipped&&!progress.reviewed.includes(progress.card)){progress.feedback=content.vocab[progress.card]?.type==='sentence'?'اقرأ الجملة وترجمتها ثم اضغط تمّت القراءة.':'اقلب البطاقة واقرأ معناها قبل المتابعة.';update();return {}}
    if(!progress.reviewed.includes(progress.card))progress.reviewed.push(progress.card);
   }
   if(phase==='listen'&&(ui.micBusy||ui.recording||progress.spoken[progress.card]?.method!=='recorded')){progress.feedback='سجّل صوتك وأوقف التسجيل قبل المتابعة.';update();return {}}
   if(progress.card>=content[phase].length-1){if(!canAdvance(content)){progress.feedback='أكمل عناصر هذا الجزء أولاً.';update();return {}}ui.playingQuestion=null;playbackToken++;window.speechSynthesis?.cancel?.();recordings.clear();progress.phase++;progress.card=0}
   else progress.card++;
   progress.flipped=false;persist();update();return {}
  }
  if(action==='menu-add'){ui.screen='add-select';ui.notice='';update();return {}}
  if(action==='menu-edit'){ui.screen='edit-select';ui.notice='';update();return {}}
  if(action==='view-imported'){if(importing.firstBox){ui.previewBox=importing.firstBox;ui.sheet=false;update()}return {}}
  if(action==='preview-box'){const id=Number(el.dataset.value);if(Number.isInteger(id)&&id>=1&&id<=1000){ui.previewBox=id;ui.sheet=false;update()}return {}}
  if(action==='close-preview'){ui.previewBox=null;update();return {}}
  if(action==='preview-audio'){const item=getContent(ui.previewBox)?.[el.dataset.process]?.[Number(el.dataset.index)];if(item?.en)speak(item.en);update();return {}}
  if(action==='back-menu'){importToken++;importing.review=null;ui.screen='menu';ui.draft=null;update();return {}}
  if(action==='process'){ui.process=el.dataset.value;ui.type=TYPES[ui.process][0][0];ui.draft=null;update();return {}}
  if(action==='type'){ui.type=el.dataset.value;ui.draft=null;update();return {}}
  if(action==='add-form'){ui.screen='form';ui.selectedId=null;ui.draft=null;update();return {}}
  if(action==='select-item'){ui.selectedId=el.dataset.id;ui.process=el.dataset.process;ui.draft=getContent(ui.targetBox)[ui.process].find(x=>x.id===ui.selectedId)||null;if(ui.draft){ui.type=ui.draft.type;ui.screen='form'}update();return {}}
  if(action==='delete-item'){ui.deleteConfirm=true;ui.draft=readEditorDraft();update();return {}}
  if(action==='cancel-delete'){ui.deleteConfirm=false;update();return {}}
  if(action==='confirm-delete'){const box=getContent(ui.targetBox);box[ui.process]=box[ui.process].filter(x=>x.id!==ui.selectedId);const stored=saveContent(ui.targetBox,box);resetAfterEdit(ui.targetBox);ui.deleteConfirm=false;ui.screen='edit-list';ui.draft=null;ui.notice=stored?'تم حذف العنصر.':'حُذف مؤقتاً؛ المتصفح منع الحفظ الدائم.';update();return {}}
  return {};
 }
 function readEditorDraft(){const form=document.getElementById('zone-item-form');if(!form)return ui.draft||{};const f=new FormData(form),draft={id:ui.selectedId||undefined,type:ui.type};for(const key of ['en','ar','example','prompt','audio','explanation','answer','title','formula','body','image'])if(f.has(key))draft[key]=String(f.get(key)||'');if(f.has('opt0')){draft.options=[0,1,2].map(i=>String(f.get(`opt${i}`)||''));draft.correct=Number(f.get('correct'))}return draft}
 function remember(target){if(!target?.name||!progress.boxId)return;const key=PHASES[progress.phase].key;const valid=getContent(progress.boxId)[key].some(item=>item.id===target.name);if(valid){progress.answers[key+':'+target.name]=String(target.value||'');persist()}}
 function submit(id,form,update){if(id==='zone-preview-form'){const target=Number(new FormData(form).get('boxId'));if(Number.isInteger(target)&&target>=1&&target<=1000){ui.previewBox=target;ui.sheet=false;update()}return {}}if(id==='zone-quiz-form'){const process=PHASES[progress.phase].key;const content=getContent(progress.boxId);const questions=content[process].filter(x=>['choice','audioChoice','write','imageChoice','imageWrite','imageSpeak'].includes(x.type));if(!questions.length){progress.feedback='لا توجد أسئلة بعد. أضف محتوى لهذا الجزء.';update();return {}}const data=new FormData(form);let correct=0;const graded=questions.filter(x=>x.type!=='imageSpeak');const spoken=questions.filter(x=>x.type==='imageSpeak');if(spoken.some(x=>!progress.imageSpoken[x.id])||ui.recording||ui.micBusy){progress.feedback='سجّل وصف كل صورة صوتياً وأوقف التسجيل قبل التسليم.';update();return {}}for(const item of graded){const answer=String(data.get(item.id)||'').trim();if(['write','imageWrite'].includes(item.type)){if(answer)progress.attempts[item.id]=(progress.attempts[item.id]||0)+1;if(norm(answer)===norm(item.answer))correct++}else if(answer!==''&&Number(answer)===item.correct)correct++}const score=graded.length?Math.round(correct/graded.length*100):100;const required=process==='exam'?75:70;const writeOkay=process!=='exam'||graded.filter(x=>['write','imageWrite'].includes(x.type)).every(x=>norm(data.get(x.id))===norm(x.answer));if(score>=required&&writeOkay){if(process==='exam'){persist();return {complete:completedData(),score}}progress.phase++;progress.card=0;progress.feedback=`أحسنت، نتيجتك ${score}%. انتقل إلى الجزء التالي.`}else progress.feedback=`حصلت على ${score}%. تحتاج ${required}%${process==='exam'?' وإجابة الكتابة صحيحة':''}. راجع المحتوى وحاول مجدداً.`;persist();update();return {}}
  if(id==='zone-jump-form'){const f=new FormData(form);const stage=Number(f.get('stage')),step=Number(f.get('step')),box=Number(f.get('box'));if([stage,step,box].every(Number.isInteger)&&stage>=1&&stage<=5&&step>=1&&step<=10&&box>=1&&box<=20){ui.targetBox=(stage-1)*200+(step-1)*20+box;ui.screen='edit-list';ui.notice='';update()}return {}}
  if(id==='zone-item-form'){const draft=readEditorDraft();try{const item=validateItem(ui.process,draft);const box=getContent(ui.targetBox||progress.boxId);const list=box[ui.process];if(ui.selectedId){const index=list.findIndex(x=>x.id===ui.selectedId);if(index<0)throw Error('العنصر لم يعد موجوداً.');list[index]=item}else{if(list.length>=MAX_ITEMS[ui.process])throw Error(`الحد الأقصى ${MAX_ITEMS[ui.process]} عنصراً في هذا الجزء.`);list.push(item)}const stored=saveContent(ui.targetBox||progress.boxId,box);resetAfterEdit(ui.targetBox||progress.boxId);ui.screen=ui.selectedId?'edit-list':'menu';ui.draft=null;ui.notice=stored?'تم حفظ المحتوى.':'تم التعديل مؤقتاً؛ المتصفح منع الحفظ الدائم.';update()}catch(error){ui.draft=draft;ui.notice=error.message;update()}return {}}
  return {};
 }
 const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const btn=(action,label,extra='')=>`<button type="button" data-zone="${action}" ${extra}>${label}</button>`;
 const speakerIcon='<svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 9a4 4 0 0 1 0 6m3-9a8 8 0 0 1 0 12"/></svg>';
 function questionAudio(item,index,process){const playing=ui.playingQuestion===process+':'+item.id;return `<div class="zone-question-audio"><div class="zone-question-audio-top"><span class="zone-question-audio-tag">مقطع صوتي · English</span><span class="zone-question-audio-hint">استمع ثم اختر المعنى</span></div><button type="button" class="zone-question-play ${playing?'is-playing':''}" data-zone="audio-question" data-process="${process}" data-index="${index}" aria-label="${playing?'إيقاف':'تشغيل'} صوت السؤال ${index+1}" aria-pressed="${playing}"><span class="zone-question-speaker">${speakerIcon}</span><span class="zone-question-play-copy"><strong>${playing?'إيقاف الاستماع':'استمع إلى السؤال'}</strong><small>${playing?'الصوت قيد التشغيل':'اضغط للتشغيل، واستمع مجدداً متى شئت'}</small></span><span class="zone-question-wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span></button></div>`}
 function imageView(item){return `<figure class="zone-image-frame"><img src="${safe(item.image)}" alt="صورة تعليمية" loading="lazy" referrerpolicy="no-referrer"><figcaption>انظر إلى الصورة</figcaption></figure>`}
 function question(item,index,process){const saved=progress.answers[process+':'+item.id],speakItem=item.type==='imageSpeak',written=['write','imageWrite'].includes(item.type),recorded=!!progress.imageSpoken[item.id];return `<fieldset class="zone-question ${item.image?'zone-image-question':''}"><legend><small>${index+1}</small> ${safe(item.prompt)}</legend>${item.image?imageView(item):''}${item.type==='audioChoice'?questionAudio(item,index,process):''}${speakItem?`<div class="zone-image-speak">${btn('image-mic',ui.recording&&capture?.index==='image:'+item.id?'إيقاف التسجيل':recorded?'أعد التسجيل':'سجّل وصف الصورة',`data-id="${safe(item.id)}" class="zone-image-mic"`)}<span>${recorded?'تم التسجيل؛ قارن نطقك بالإجابة.':'اضغط مجدداً لإيقاف الميكروفون.'}</span>${recorded?btn('image-audio',speakerIcon,`data-id="${safe(item.id)}" aria-label="استمع للإجابة"`):''}</div>`:written?`<label>إجابتك بالإنجليزية<input name="${safe(item.id)}" value="${safe(saved||'')}" dir="ltr" required placeholder="Write your answer"></label>`:`<div class="zone-options">${item.options.map((choice,i)=>`<label><input type="radio" name="${safe(item.id)}" value="${i}" ${saved===String(i)?'checked':''} required><span>${safe(choice)}</span></label>`).join('')}</div>`}</fieldset>`}
 function quiz(content,process,title,intro){const questions=content[process].filter(x=>['choice','audioChoice','write','imageChoice','imageWrite','imageSpeak'].includes(x.type));return `<section class="zone-panel zone-quiz"><div class="zone-section-head"><span class="zone-kicker">محطة الفهم</span><h1>${title}</h1><p>${intro}</p></div>${questions.length?`<form id="zone-quiz-form">${questions.map((q,i)=>question(q,i,process)).join('')}<button class="zone-primary" type="submit">تحقّق وانتقل</button></form>`:'<div class="zone-empty">أضف سؤالاً من إدارة المحتوى.</div>'}</section>`}
 function vocabulary(content){const list=content.vocab,item=list[progress.card],sentence=item?.type==='sentence',reviewed=progress.reviewed.includes(progress.card);return `<section class="zone-panel zone-vocab"><div class="zone-section-head"><span class="zone-kicker">01 / مفردات</span><h1>${sentence?'الجملة في سياقها.':'كلمة جديدة، مساحة أكبر.'}</h1><p>${sentence?'اقرأ الجملة والترجمة ثم استمع لها.':'استمع إلى الكلمة، حاول تذكّر المعنى ثم اقلب البطاقة.'}</p></div>${item?`<div class="zone-count">البطاقة ${progress.card+1} من ${list.length}<span>${sentence?'جملة':'كلمة'}</span></div>${sentence?`<article class="zone-sentence"><div class="zone-sentence-label">ENGLISH · SENTENCE</div><p lang="en" dir="ltr">${safe(item.en)}</p><div class="zone-sentence-translation"><small>المعنى بالعربية</small><strong>${safe(item.ar)}</strong></div><div class="zone-sentence-example" dir="ltr">${safe(item.example)}</div></article><div class="zone-sentence-tools">${btn('audio',speakerIcon+' استمع للجملة',`data-index="${progress.card}"`)}${btn('mark-sentence',reviewed?'تمّت القراءة ✓':'تمّت القراءة',reviewed?'disabled':'')}</div>`:`<div class="zone-flash-wrap">${item.image?imageView(item):''}<button class="zone-flash ${progress.flipped?'is-flipped':''}" type="button" data-zone="flip" aria-label="اقلب البطاقة"><span class="zone-flash-hint">${progress.flipped?'الترجمة العربية':'اضغط لإظهار المعنى'}</span><strong dir="${progress.flipped?'rtl':'ltr'}">${safe(progress.flipped?item.ar:item.en)}</strong><small>${progress.flipped?safe(item.example):'ENGLISH → العربية'}</small></button>${!progress.flipped?btn('replay-word',speakerIcon+' استمع مجدداً','class="zone-word-audio" aria-label="استمع للكلمة مجدداً"'):''}</div>`}<div class="zone-simple-nav">${btn('prev','السابق',progress.card===0?'disabled':'')}${btn('next','التالي',progress.flipped||reviewed?'class="zone-primary"':'class="zone-primary" disabled')}</div><p class="zone-card-progress">${progress.reviewed.length} / ${list.length} عناصر تمت مراجعتها</p>`:'<div class="zone-empty">هذا الجزء ينتظر بطاقاتك. افتح إدارة المحتوى لإضافة كلمة أو جملة.</div>'}</section>`}
 function listening(content){const list=content.listen,item=list[progress.card],ready=progress.spoken[progress.card]?.method==='recorded',active=ui.recording&&capture?.index===progress.card;return `<section class="zone-panel zone-listen"><div class="zone-section-head"><span class="zone-kicker">02 / استمع وتكلّم</span><h1>اسمع ثم سجّل صوتك.</h1><p>استمع للعبارة، ثم اضغط الميكروفون للتسجيل. اضغطه ثانية لإنهاء المحاولة.</p></div>${item?`<div class="zone-count">المقطع ${progress.card+1} من ${list.length}<span>${item.type==='sentence'?'جملة':'كلمة'}</span></div>${item.image?imageView(item):''}<div class="zone-pronounce-word"><strong dir="ltr">${safe(item.en)}</strong><span>${safe(item.ar)}</span></div><div class="zone-pronounce-pair"><button type="button" data-zone="audio" data-index="${progress.card}" class="zone-pronounce-tile zone-hear" aria-label="استمع إلى ${safe(item.en)}" title="استمع إلى العبارة">${speakerIcon}</button><button type="button" data-zone="mic" data-index="${progress.card}" class="zone-pronounce-tile zone-say ${active?'is-recording':ready?'is-done':''}" ${ui.micBusy?'disabled':''} aria-label="${active?'أوقف تسجيل صوتك':ready?'سجّل محاولة جديدة':'ابدأ تسجيل صوتك'}" aria-pressed="${active}" title="${active?'أوقف التسجيل':ready?'محاولة جديدة':'ابدأ التسجيل'}"><svg width="37" height="37" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5m-4 0h8"/></svg></button></div><p class="zone-record-status" role="status">${ui.micBusy?'بانتظار الميكروفون أو إغلاق التسجيل…':active?'التسجيل جارٍ · اضغط الميكروفون لإيقافه':ready?'تم تسجيل محاولتك · اضغط الميكروفون لتسجيل محاولة جديدة':'اضغط الصوت للاستماع، ثم الميكروفون للتسجيل. يُحفظ إنجاز المقطع فقط، لا الملف الصوتي.'}</p><div class="zone-simple-nav">${btn('prev','السابق',progress.card===0||ui.micBusy||ui.recording?'disabled':'')}${btn('next','التالي',ready&&!ui.micBusy&&!ui.recording?'class="zone-primary"':'class="zone-primary" disabled')}</div><p class="zone-card-progress">${Object.values(progress.spoken).filter(x=>x.method==='recorded').length} / ${list.length} مقاطع · بعد الأخير يبدأ فحص السمع تلقائياً</p>`:'<div class="zone-empty">أضف مقطع كلمة أو جملة من إدارة المحتوى لتبدأ.</div>'}</section>`}
 function grammar(content){const items=content.grammar,rules=items.filter(x=>['sentenceRule','questionRule'].includes(x.type)),supports=items.filter(x=>['note','addition','example'].includes(x.type));const first=rules.find(x=>x.type==='sentenceRule')||rules[0];const generic=/^(كيف تنشئ (جملة|سؤال)؟|قانون (الجملة|السؤال))$/;const title=first?(generic.test(first.title)?'قاعدة: '+first.formula:first.title):'قواعد هذا الصندوق';const ruleView=(item,i)=>{const parts=item.formula.split('+');return `<article class="zone-rule"><div class="zone-rule-top"><span>${String(i+1).padStart(2,'0')} / ${item.type==='questionRule'?'صياغة السؤال':'بناء الجملة'}</span><span>${item.type==='questionRule'?'؟':'A → B'}</span></div><h2>${safe(item===first?item.type==='questionRule'?'صيغة السؤال':'صيغة الجملة':item.title)}</h2><p>${item.type==='questionRule'?'استخدم هذا الترتيب عندما تريد الاستفسار.':'استخدم هذا الترتيب لتكوين جملة عن نفسك.'}</p><div class="zone-rule-formula" dir="auto">${parts.map((part,j)=>`<span>${safe(part.trim())}</span>${j<parts.length-1?'<b aria-hidden="true">+</b>':''}`).join('')}</div><div class="zone-rule-example"><small>انظر إلى المثال</small><strong dir="ltr">${safe(item.example)}</strong><p>${safe(item.body)}</p></div></article>`};const supportView=item=>`<article class="zone-grammar-support ${safe(item.type)}"><span>${item.type==='note'?'لاحظ':item.type==='addition'?'جرّب الآن':'مثال إضافي'}</span>${item.image?imageView(item):''}${item.title?`<h3>${safe(item.title)}</h3>`:''}${item.en?`<strong dir="ltr">${safe(item.en)}</strong><small>${safe(item.ar)}</small>`:''}<p>${safe(item.body)}</p></article>`;return `<section class="zone-panel zone-grammar"><div class="zone-section-head zone-grammar-head"><span class="zone-kicker">03 / دليل القواعد</span><h1>${safe(title)}</h1><p>تعلّم ترتيب الكلمات من قاعدة الصندوق، قارن المثال، ثم طبّق ما فهمته.</p><div class="zone-grammar-journey"><span>١ · افهم الصيغة</span><span>٢ · اقرأ المثال</span><span>٣ · لاحظ وطبّق</span></div></div><div class="zone-rule-grid">${rules.length?rules.map(ruleView).join(''):'<div class="zone-empty">أضف قانوناً للجملة أو السؤال من إدارة المحتوى.</div>'}</div>${supports.length?`<div class="zone-grammar-supports">${supports.map(supportView).join('')}</div>`:''}<div class="zone-grammar-test"><span class="zone-kicker">التحقق الأخير</span><h2>هل يمكنك تمييز الترتيب الصحيح؟</h2><p>استخدم القاعدة والمثال أعلاه عند الحاجة. يظهر التصحيح بعد الإجابة.</p>${items.some(x=>x.type==='choice')?`<form id="zone-quiz-form">${items.filter(x=>x.type==='choice').map((x,i)=>question(x,i,'grammar')).join('')}<button class="zone-primary" type="submit">تحقّق وانتقل إلى الامتحان</button></form>`:'<div class="zone-empty">أضف سؤالاً للقواعد للانتقال إلى الامتحان.</div>'}</div></section>`}
 function field(name,label,value='',kind='input'){return `<label>${label}${kind==='textarea'?`<textarea name="${name}" maxlength="500" required>${safe(value)}</textarea>`:`<input name="${name}" value="${safe(value)}" maxlength="300" required dir="auto">`}</label>`}
 function editorForm(){const d=ui.draft||{},type=ui.type;let inputs='';
  if(['word','sentence','imageWord'].includes(type)&&ui.process==='vocab')inputs=field('en','النص بالإنجليزية',d.en)+field('ar','المعنى بالعربية',d.ar)+field('example','مثال بالإنجليزية',d.example);
  else if(ui.process==='listen')inputs=field('en','النص الذي سيُقرأ بالإنجليزية',d.en)+field('ar','المعنى بالعربية',d.ar);
  else if(['choice','audioChoice','imageChoice'].includes(type))inputs=field('prompt','نص السؤال',d.prompt)+(type==='audioChoice'?field('audio','النص الصوتي بالإنجليزية',d.audio):'')+[0,1,2].map(i=>field('opt'+i,'الخيار '+(i+1),d.options?.[i])).join('')+`<label>الإجابة الصحيحة<select name="correct">${[0,1,2].map(i=>`<option value="${i}" ${Number(d.correct||0)===i?'selected':''}>الخيار ${i+1}</option>`).join('')}</select></label>`+field('explanation','شرح الإجابة',d.explanation);
  else if(['write','imageWrite','imageSpeak'].includes(type))inputs=field('prompt','تعليمات السؤال',d.prompt)+field('answer','الإجابة الصحيحة بالإنجليزية',d.answer)+field('explanation','شرح الإجابة',d.explanation);
  else if(['sentenceRule','questionRule'].includes(type))inputs=field('title','عنوان القانون',d.title)+field('formula','صيغة القانون',d.formula)+field('body','الشرح',d.body,'textarea')+field('example','مثال بالإنجليزية',d.example);
  else if(['note','addition'].includes(type))inputs=field('title','العنوان',d.title)+field('body','المحتوى',d.body,'textarea');
  else if(type==='example')inputs=field('en','المثال بالإنجليزية',d.en)+field('ar','ترجمته بالعربية',d.ar)+field('body','شرح المثال',d.body,'textarea');
  if(type.startsWith('image'))inputs+=field('image','رابط الصورة المباشر (https://)',d.image);
  return `<form id="zone-item-form" class="zone-editor-form">${inputs}<div class="zone-editor-actions"><button type="submit" class="zone-primary">حفظ العنصر</button>${ui.selectedId?btn('delete-item','حذف العنصر','class="zone-danger"'):''}</div></form>${ui.deleteConfirm?`<div class="zone-confirm"><p>هل تريد حذف هذا العنصر؟</p>${btn('confirm-delete','نعم، احذف','class="zone-danger"')}${btn('cancel-delete','إلغاء')}</div>`:''}`}
 function editor(){if(!ui.sheet)return '';const target=ui.targetBox||progress.boxId,content=getContent(target);let body='';
  if(ui.screen==='menu'){const available=Object.keys(contentEdits).map(Number).filter(id=>Object.values(contentEdits[id]).some(list=>list.length)).sort((a,b)=>a-b);body=`<p>خصّص محتوى التعلّم في متصفحك.</p><div class="zone-menu">${btn('menu-add','إضافة محتوى تعليمي <small>اختر العملية ونوع العنصر</small>')}${btn('menu-edit','تعديل عنصر <small>اختر المرحلة والخطوة والصندوق</small>')}<label class="zone-import-direct" for="zone-import-file"><strong>استيراد محتوى من Excel</strong><small>اختر ملف .xlsx · إضافة العناصر الجديدة دون حذف الموجود</small><input id="zone-import-file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" aria-label="استيراد محتوى من ملف Excel" ${importing.busy?'disabled':''}></label></div>${importing.busy?'<p role="status" class="zone-import-status">جارٍ قراءة الملف وإضافة العناصر…</p>':''}${importing.error?`<p role="alert" class="zone-import-error">${safe(importing.error)}</p>`:''}<a class="zone-import-template" href="liplip-content-template.xlsx" download>تنزيل قالب Excel ↓</a>${available.length?`<div class="zone-saved-boxes"><h3>صناديق محفوظة في هذا المتصفح</h3><p>اختر صندوقاً لمعاينة محتواه. الصندوق المفتوح للتعلّم الآن: ${safe(progress.boxId)}.</p><form id="zone-preview-form"><select name="boxId" aria-label="اختر الصندوق المحفوظ">${available.map(id=>{const p=LiplipProgress.location(id);return `<option value="${id}">المستوى ${p.stage} · الخطوة ${p.step} · الصندوق ${p.box}</option>`}).join('')}</select><button type="submit" class="zone-primary">معاينة الدرس</button></form></div>`:''}`}
  if(ui.screen==='import-result')body=`<div class="zone-import-done" role="status"><span aria-hidden="true">✓</span><h3>${ui.notice.startsWith('أُضيف 0')?'المحتوى موجود بالفعل':'اكتمل الاستيراد'}</h3><p>${safe(ui.notice)}</p><small>لم يُحذف أو يُستبدل أي عنصر موجود. المحتوى محفوظ في هذا المتصفح.</small></div>${importing.firstBox!==progress.boxId?`<p class="zone-import-location">الدرس المفتوح الآن هو الصندوق ${safe(progress.boxId)}، والملف يشير إلى الصندوق ${safe(importing.firstBox)}. لذلك لن ترى هذه العناصر عند إغلاق النافذة والعودة إلى درسك الحالي.</p>`:''}<div class="zone-editor-actions">${btn('view-imported','معاينة الدرس في الصندوق المستورد','class="zone-primary"')}${btn('back-menu','استيراد ملف آخر')}</div>`;
  if(ui.screen==='add-select')body=`<p>اختر الجزء، ثم نوع المحتوى.</p><div class="zone-editor-tabs">${Object.keys(TYPES).map(key=>btn('process',PROCESS_LABEL[key],`data-value="${key}" class="${ui.process===key?'selected':''}"`)).join('')}</div><div class="zone-editor-tabs">${TYPES[ui.process].map(([key,label])=>btn('type',label,`data-value="${key}" class="${ui.type===key?'selected':''}"`)).join('')}</div>${btn('add-form','متابعة إلى النموذج','class="zone-primary"')}`;
  if(ui.screen==='edit-select'){const n=target-1,stage=Math.floor(n/200)+1,step=Math.floor(n%200/20)+1,box=n%20+1;body=`<p>اختر موقع الصندوق الذي تريد تحريره.</p><form id="zone-jump-form" class="zone-location">${[['stage','المرحلة',5,stage],['step','الخطوة',10,step],['box','الصندوق',20,box]].map(([key,label,max,current])=>`<label>${label}<select name="${key}">${Array.from({length:max},(_,i)=>`<option value="${i+1}" ${i+1===current?'selected':''}>${i+1}</option>`).join('')}</select></label>`).join('')}<button class="zone-primary" type="submit">عرض العناصر</button></form>`}
  if(ui.screen==='edit-list')body=`<p>المرحلة ${Math.floor((target-1)/200)+1} · الخطوة ${Math.floor((target-1)%200/20)+1} · الصندوق ${(target-1)%20+1}</p>${btn('preview-box','معاينة هذا الصندوق',`data-value="${target}" class="zone-primary"`)}<div class="zone-item-list">${Object.keys(TYPES).map(key=>`<h3>${PROCESS_LABEL[key]}</h3>${content[key].length?content[key].map(item=>btn('select-item',safe(item.title||item.en||item.prompt||item.audio||item.type),`data-process="${key}" data-id="${safe(item.id)}"`)).join(''):'<p>لا توجد عناصر بعد.</p>'}`).join('')}</div>${btn('menu-edit','تغيير الصندوق')}`;
  if(ui.screen==='form')body=`<p>${ui.selectedId?'تعديل العنصر المحدد':'عنصر جديد'} · ${PROCESS_LABEL[ui.process]} · الصندوق ${(target-1)%20+1}</p>${editorForm()}`;
  return `<div class="zone-overlay"><button type="button" class="zone-backdrop" data-zone="close-sheet" aria-label="إغلاق إدارة المحتوى"></button><section class="zone-sheet" role="dialog" aria-modal="true" aria-label="إدارة محتوى التعلّم"><div class="zone-sheet-head"><div><small>STUDIO / LIPLIP</small><h2>إدارة المحتوى</h2></div>${btn('close-sheet','إغلاق','class="zone-close" aria-label="إغلاق نافذة المحتوى"')}</div>${ui.screen!=='menu'?btn('back-menu','القائمة الرئيسية','class="zone-back"'):''}${ui.notice&&ui.screen!=='import-result'?`<p class="zone-notice" role="status">${safe(ui.notice)}</p>`:''}${body}</section></div>`}
 function preview({snapshot}){const id=ui.previewBox,location=LiplipProgress.location(id),content=getContent(id),total=Object.values(content).reduce((sum,items)=>sum+items.length,0);const itemView=(item,process,index)=>`<article class="zone-preview-item"><div class="zone-preview-item-head"><small>${safe(TYPES[process].find(([type])=>type===item.type)?.[1]||item.type)}</small>${item.en?btn('preview-audio',speakerIcon,`data-process="${process}" data-index="${index}" aria-label="استمع إلى ${safe(item.en)}"`):''}</div>${item.image?imageView(item):''}${item.title?`<h3>${safe(item.title)}</h3>`:''}${item.en?`<strong dir="ltr">${safe(item.en)}</strong>`:''}${item.ar?`<p>${safe(item.ar)}</p>`:''}${item.formula?`<p class="zone-preview-formula" dir="auto">${safe(item.formula)}</p>`:''}${item.prompt?`<h3>${safe(item.prompt)}</h3>`:''}${item.audio?`<p dir="ltr">${safe(item.audio)}</p>`:''}${item.options?`<ol>${item.options.map((option,i)=>`<li class="${i===item.correct?'is-answer':''}">${safe(option)}${i===item.correct?' · الإجابة الصحيحة':''}</li>`).join('')}</ol>`:''}${item.answer?`<p>الإجابة: <strong dir="ltr">${safe(item.answer)}</strong></p>`:''}${item.example?`<p dir="ltr">${safe(item.example)}</p>`:''}${item.body?`<p>${safe(item.body)}</p>`:''}${item.explanation?`<p>${safe(item.explanation)}</p>`:''}</article>`;return `<div class="zone zone-preview"><header class="zone-header">${btn('close-preview','العودة إلى درسي','class="zone-exit"')}<div class="zone-brand" dir="ltr">lip<span>lip</span></div><span class="zone-save">معاينة المحتوى المحفوظ</span></header><main class="zone-main"><div class="zone-preview-intro"><span class="zone-kicker">معاينة صندوق التعلّم</span><h1>${safe(LiplipProgress.BOX_NAMES[location.box-1])}</h1><p>المستوى ${location.stage} · الخطوة ${location.step} · الصندوق ${location.box} · ${total} عنصراً</p>${id!==progress.boxId?`<div class="zone-preview-note">الصندوق الجاري في دراستك هو ${safe(progress.boxId)}. هذه معاينة للصندوق ${id}؛ لا تغيّر موقعك أو تقدّمك.</div>`:''}</div>${Object.keys(TYPES).filter(process=>content[process].length).map(process=>`<section class="zone-preview-section"><div class="zone-preview-section-title"><h2>${PROCESS_LABEL[process]}</h2><span>${content[process].length} عناصر</span></div><div class="zone-preview-items">${content[process].map((item,i)=>itemView(item,process,i)).join('')}</div></section>`).join('')||'<div class="zone-empty">لا يحتوي هذا الصندوق على عناصر بعد.</div>'}</main>${btn('control','إدارة المحتوى','class="zone-control"')}${editor()}</div>`}
 function render({snapshot}){if(ui.previewBox)return preview({snapshot});const content=getContent(progress.boxId),phase=PHASES[progress.phase];const body=phase.key==='vocab'?vocabulary(content):phase.key==='listen'?listening(content):phase.key==='grammar'?grammar(content):quiz(content,phase.key,phase.key==='exam'?'أثبت ما تعلّمته.':phase.key==='checkpointVocab'?'هل استقرّت الكلمات؟':'هل سمعت المعنى؟',phase.key==='exam'?'أسئلة مفردات وقواعد وكتابة؛ تحتاج ٧٥٪ وإجابة الكتابة الصحيحة.':'اختبار قصير قبل الجزء التالي؛ تحتاج ٧٠٪.');return `<div class="zone zone-${phase.key}"><header class="zone-header">${btn('exit','الخروج من الصندوق','class="zone-exit"')}<div class="zone-brand" dir="ltr">lip<span>lip</span></div><span class="zone-save">تقدّمك يُحفظ تلقائياً</span></header><main class="zone-main"><div class="zone-context"><span>${safe(snapshot?.level||'A0')} · المرحلة ${safe(snapshot?.position?.stage||1)} / الخطوة ${safe(snapshot?.position?.step||1)}</span><strong>${safe(snapshot?.boxName||'صندوق التعلّم')}</strong></div><nav class="zone-track" aria-label="مراحل الصندوق">${PHASES.map((p,i)=>`<span class="${i===progress.phase?'current':i<progress.phase?'done':''}" ${i===progress.phase?'aria-current="step"':''}><i>${String(i+1).padStart(2,'0')}</i>${p.name}</span>`).join('')}</nav>${body}${progress.feedback?`<p class="zone-feedback" role="status">${safe(progress.feedback)}</p>`:''}</main>${btn('control','إدارة المحتوى','class="zone-control" aria-label="إدارة المحتوى التعليمي"')}${editor()}</div>`}
 function afterRender(){if(progress.boxId&&PHASES[progress.phase]?.key==='vocab'&&!ui.previewBox){const item=getContent(progress.boxId).vocab[progress.card];if(item&&item.type!=='sentence'&&!progress.flipped){const key=[progress.boxId,progress.revision,progress.card,item.id].join(':');if(lastAutoWord!==key){lastAutoWord=key;speak(item.en)}}}}
 return {start,render,afterRender,click,submit,remember,clear,importFile,getContent,validateItem,PHASES,TYPES,MAX_ITEMS};
})();
